import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "document-tools";

export const documentLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "markdown-to-html",
    slug: "markdown-to-html",
    title: "Markdown to HTML Converter",
    category,
    subcategory: "markup-converters",
    shortDescription: "Convert Markdown documents to HTML markup.",
    metaTitle: "Markdown to HTML Converter - Convert MD Online",
    metaDescription: "Convert Markdown to HTML online. Paste Markdown and copy basic HTML output in your browser.",
    keywords: ["markdown to html", "md to html", "markdown converter"],
    relatedTools: ["html-to-markdown", "word-count-document", "text-to-pdf"],
    componentKey: "GenericDocumentTool",
    explanation: "Paste Markdown text and convert common headings, lists, and emphasis to HTML.",
    howToUse: ["Paste Markdown source.", "View HTML output instantly.", "Copy the generated HTML."],
    examples: [{ title: "Heading and list", input: "# Title\n- item one", output: "<h1>Title</h1>\n<ul><li>item one</li></ul>", explanation: "Supports # headings, lists, bold, and italic." }],
    faqs: [
      faq("What Markdown syntax is supported?", "Headings (#), bold (**), italic (*), unordered lists (-), and paragraphs."),
      faq("Are tables supported?", "Complex tables and nested structures may not convert fully."),
      faq("Is GitHub Flavored Markdown supported?", "Partial support only; code fences and GFM extensions are limited."),
    ],
    commonUseCases: ["Draft blog HTML from Markdown notes", "Convert README snippets", "Quick HTML preview for docs"],
    assumptions: ["Best for simple Markdown documents.", "Not a full CommonMark parser."],
  }),
  buildLiveTool({
    id: "html-to-markdown",
    slug: "html-to-markdown",
    title: "HTML to Markdown Converter",
    category,
    subcategory: "markup-converters",
    shortDescription: "Convert HTML snippets into Markdown text.",
    metaTitle: "HTML to Markdown Converter - Convert HTML Online",
    metaDescription: "Convert HTML snippets to Markdown text online. Free HTML to Markdown converter in your browser.",
    keywords: ["html to markdown", "html converter", "html to md"],
    relatedTools: ["markdown-to-html", "word-count-document", "text-to-pdf"],
    componentKey: "GenericDocumentTool",
    explanation: "Paste HTML and get a simplified Markdown version for docs and notes.",
    howToUse: ["Paste HTML snippet.", "View simplified Markdown output.", "Copy for use in docs or CMS."],
    examples: [{ title: "Paragraph and heading", input: "<h2>Section</h2><p>Hello <strong>world</strong></p>", output: "## Section\n\nHello **world**", explanation: "Common tags convert to Markdown equivalents." }],
    faqs: [
      faq("Will formatting be perfect?", "Complex HTML may produce simplified or lossy Markdown."),
      faq("Are attributes preserved?", "No. Links and images convert to basic Markdown where detected."),
      faq("Can I convert full web pages?", "Best for small HTML snippets, not entire page layouts."),
    ],
    commonUseCases: ["Migrate CMS content to Markdown", "Clean pasted HTML from Word", "Convert email HTML to plain docs"],
    assumptions: ["Strip-tags approach for common elements.", "Nested or custom HTML may need manual cleanup."],
  }),
  buildLiveTool({
    id: "word-count-document",
    slug: "word-count-document",
    title: "Document Word Counter",
    category,
    subcategory: "document-utilities",
    shortDescription: "Count words, characters, and lines in document text.",
    metaTitle: "Document Word Counter - Count Words Online",
    metaDescription: "Count words, characters, and lines in pasted document text. Free document word counter.",
    keywords: ["document word count", "word counter", "character count document"],
    relatedTools: ["word-counter", "markdown-to-html", "text-to-pdf"],
    componentKey: "GenericDocumentTool",
    explanation: "Paste document text to see word, character, and line counts instantly.",
    howToUse: ["Paste or type document text.", "View word, character, and line counts.", "Use counts for writing limits or SEO."],
    examples: [{ title: "Short paragraph", input: "The quick brown fox jumps over the lazy dog.", output: "9 words, 44 characters", explanation: "Counts split on whitespace for words." }],
    faqs: [
      faq("How are words counted?", "Sequences separated by whitespace count as words."),
      faq("Do punctuation affect character count?", "Yes. All characters including spaces are counted."),
      faq("Is this different from the text word counter?", "Similar logic; this tool is grouped under document utilities."),
    ],
    commonUseCases: ["Check essay word limits", "Estimate reading time", "Validate meta description length"],
  }),
  buildLiveTool({
    id: "text-to-pdf",
    slug: "text-to-pdf",
    title: "Text to PDF Converter",
    category,
    subcategory: "document-utilities",
    shortDescription: "Convert plain text into a downloadable PDF.",
    metaTitle: "Text to PDF Converter - Export Text as PDF",
    metaDescription: "Convert plain text to a downloadable PDF file online. Free text to PDF converter in your browser.",
    keywords: ["text to pdf", "plain text to pdf", "txt to pdf"],
    relatedTools: ["word-count-document", "pdf-merge", "markdown-to-html"],
    componentKey: "GenericDocumentTool",
    explanation: "Paste plain text and download a simple PDF document generated in your browser.",
    howToUse: ["Paste plain text.", "Click generate.", "Download the PDF file."],
    examples: [{ title: "Meeting notes", input: "Meeting notes\n\n- Item one\n- Item two", output: "Single-page PDF", explanation: "Line breaks are preserved in the PDF layout." }],
    faqs: [
      faq("Does it support formatting?", "Plain text only; no bold, images, or custom fonts."),
      faq("Is there a page limit?", "Very long text may span multiple pages depending on length."),
      faq("Does text leave my browser?", "No. PDF generation runs locally using pdf-lib."),
    ],
    commonUseCases: ["Export notes as PDF", "Create simple printable documents", "Share text in PDF format"],
  }),
  buildLiveTool({
    id: "pdf-merge",
    slug: "pdf-merge",
    title: "PDF Merge Pro",
    category,
    subcategory: "pdf-tools",
    shortDescription: "Combine multiple PDF files into one document with reorder and local processing.",
    metaTitle: "PDF Merge Pro - Combine PDF Files Online",
    metaDescription: "Merge multiple PDF files in your browser. Reorder files, track progress, and download — nothing uploaded to a server.",
    keywords: ["pdf merge", "combine pdf", "merge pdf files"],
    relatedTools: ["pdf-split", "text-to-pdf", "word-count-document"],
    componentKey: "PdfMergeTool",
    explanation: "Select two or more PDF files and download a merged PDF in page order.",
    howToUse: ["Select multiple PDF files.", "Click merge.", "Download the combined PDF."],
    examples: [
      { title: "Merge two reports", input: "report-a.pdf + report-b.pdf", output: "combined.pdf", explanation: "Pages from file A followed by pages from file B." },
      { title: "Reorder before merge", input: "appendix.pdf, cover.pdf, body.pdf", output: "combined.pdf", explanation: "Drag files into order in the list, then merge." },
    ],
    faqs: [
      faq("Is there a file size limit?", "Large files depend on browser memory; keep batches reasonable."),
      faq("Can I reorder files?", "Yes. Reorder the file list before merging; page order follows file order."),
      faq("Are PDFs uploaded to a server?", "No. Merging runs locally in your browser."),
      faq("How many PDFs can I merge?", "Up to 20 files per batch in the browser UI."),
    ],
    commonUseCases: ["Combine scanned documents", "Merge contract appendices", "Join report sections"],
    lastReviewed: "2026-06-02",
  }),
  buildLiveTool({
    id: "pdf-split",
    slug: "pdf-split",
    title: "PDF Split Pro",
    category,
    subcategory: "pdf-tools",
    shortDescription: "Split PDF pages by range or into separate files — processed locally in your browser.",
    metaTitle: "PDF Split Pro - Split PDF Pages Online",
    metaDescription: "Split PDF pages by range (1-3, 5) or all pages. Free browser-based PDF split with no upload.",
    keywords: ["pdf split", "split pdf pages", "pdf splitter"],
    relatedTools: ["pdf-merge", "text-to-pdf", "word-count-document"],
    componentKey: "PdfSplitTool",
    explanation: "Upload a PDF and download each page as its own PDF file.",
    howToUse: ["Upload a PDF file.", "Click split.", "Download individual page PDFs."],
    examples: [
      { title: "All pages", input: "document.pdf, range: all", output: "One PDF per page", explanation: "Each page downloads as its own file." },
      { title: "Page range", input: "document.pdf, range: 1-3, 5", output: "Pages 1–3 and 5 only", explanation: "Use comma-separated ranges; omit pages you do not need." },
    ],
    faqs: [
      faq("Can I split a page range?", "Yes. Enter all for every page, or ranges like 1-3, 5 for specific pages."),
      faq("Will quality decrease?", "No recompression; pages are extracted as-is."),
      faq("Does it work with encrypted PDFs?", "Password-protected PDFs may not split without unlocking first."),
      faq("Can I merge extracted pages again?", "Yes. Use PDF merge after splitting to combine selected outputs."),
    ],
    commonUseCases: ["Extract single pages from scans", "Separate multi-page invoices", "Share one page from a report"],
    lastReviewed: "2026-06-02",
  }),
];
