import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "design-tools";

export const designLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "color-converter",
    slug: "color-converter",
    title: "Color Converter",
    category,
    subcategory: "color-tools",
    shortDescription: "Convert HEX colors to RGB and HSL values.",
    metaTitle: "Color Converter - HEX to RGB and HSL",
    metaDescription: "Convert HEX colors to RGB and HSL online. Free color converter for designers and developers.",
    keywords: ["color converter", "hex to rgb", "hex to hsl"],
    relatedTools: ["contrast-checker", "gradient-generator", "rem-to-px"],
    componentKey: "GenericDesignTool",
    explanation: "Paste a hex color to get matching RGB and HSL values for CSS and design tools.",
    howToUse: ["Enter a hex color (with or without #).", "View RGB and HSL equivalents.", "Copy values for your stylesheet."],
    examples: [{ title: "Brand blue", input: "#2563EB", output: "rgb(37, 99, 235); hsl(221, 83%, 53%)", explanation: "Common Tailwind blue-600 converted to RGB and HSL." }],
    faqs: [
      faq("Do I need the # prefix?", "Both #2563EB and 2563EB are accepted."),
      faq("Are short hex codes supported?", "Three-digit hex like #FFF expands to six digits."),
      faq("Can I convert RGB back to hex?", "Enter hex here; use your design tool for reverse conversion."),
    ],
    commonUseCases: ["Convert design token colors", "Match brand palette to CSS", "Share color specs with developers"],
  }),
  buildLiveTool({
    id: "contrast-checker",
    slug: "contrast-checker",
    title: "Contrast Checker",
    category,
    subcategory: "color-tools",
    shortDescription: "Check WCAG contrast ratios for text and backgrounds.",
    metaTitle: "Contrast Checker - WCAG Color Contrast Ratio",
    metaDescription: "Check WCAG contrast ratios between text and background colors. Free accessibility contrast checker.",
    keywords: ["contrast checker", "wcag contrast", "color contrast ratio"],
    relatedTools: ["color-converter", "gradient-generator", "rem-to-px"],
    componentKey: "GenericDesignTool",
    explanation: "Compare foreground and background hex colors for WCAG AA and AAA readability ratios.",
    howToUse: ["Enter text (foreground) color.", "Enter background color.", "View contrast ratio and WCAG pass/fail."],
    examples: [{ title: "Black on white", input: "text #000000, bg #FFFFFF", output: "21:1 ratio, passes AAA", explanation: "Maximum contrast for body text." }],
    faqs: [
      faq("What ratio is required for AA?", "4.5:1 for normal text, 3:1 for large text (18pt+ or 14pt bold)."),
      faq("What about AAA?", "7:1 for normal text, 4.5:1 for large text."),
      faq("Does it check UI components?", "Enter colors for text and background; non-text UI needs 3:1 for AA."),
    ],
    commonUseCases: ["Validate accessible text colors", "Check button label contrast", "Audit design system palettes"],
    sourceNotes: ["WCAG 2.1 contrast requirements (W3C).", "Large text: 18pt+ regular or 14pt+ bold."],
  }),
  buildLiveTool({
    id: "gradient-generator",
    slug: "gradient-generator",
    title: "Gradient Generator",
    category,
    subcategory: "generators",
    shortDescription: "Create CSS linear gradient backgrounds.",
    metaTitle: "Gradient Generator - CSS Linear Gradient Tool",
    metaDescription: "Generate CSS linear gradient code from two colors and an angle. Free gradient generator for web design.",
    keywords: ["gradient generator", "css gradient", "linear gradient generator"],
    relatedTools: ["color-converter", "contrast-checker", "spacing-scale-generator"],
    componentKey: "GenericDesignTool",
    explanation: "Pick two colors and an angle to generate copy-ready CSS linear-gradient code.",
    howToUse: ["Enter start and end hex colors.", "Set gradient angle in degrees.", "Copy the CSS background property."],
    examples: [{ title: "Blue to purple at 135°", input: "#2563EB → #7C3AED, 135deg", output: "linear-gradient(135deg, #2563EB, #7C3AED)", explanation: "Diagonal gradient common in hero sections." }],
    faqs: [
      faq("Can I preview the gradient?", "The output CSS can be pasted into your stylesheet for preview."),
      faq("Does it support radial gradients?", "This tool generates linear gradients only."),
      faq("What angle values work?", "0–360 degrees; 0 is bottom-to-top, 90 is left-to-right."),
    ],
    commonUseCases: ["Hero section backgrounds", "Button hover effects", "Design system gradient tokens"],
  }),
  buildLiveTool({
    id: "spacing-scale-generator",
    slug: "spacing-scale-generator",
    title: "Spacing Scale Generator",
    category,
    subcategory: "layout-tools",
    shortDescription: "Generate consistent spacing scales for design systems.",
    metaTitle: "Spacing Scale Generator - Design System Spacing",
    metaDescription: "Generate spacing scales from a base value for design systems and UI layouts. Free spacing scale tool.",
    keywords: ["spacing scale", "design tokens", "spacing generator"],
    relatedTools: ["rem-to-px", "px-to-rem", "gradient-generator"],
    componentKey: "GenericDesignTool",
    explanation: "Build a simple px spacing scale from a base increment and step count.",
    howToUse: ["Enter base spacing increment in px.", "Set number of steps.", "Copy the generated scale values."],
    examples: [{ title: "4px base, 8 steps", input: "base=4, steps=8", output: "4, 8, 12, 16, 20, 24, 28, 32 px", explanation: "Common 4px grid system spacing." }],
    faqs: [
      faq("Can I use rem instead?", "Output is in px; convert with rem-to-px using your root font size."),
      faq("Is this a geometric scale?", "Linear increment from base × step number."),
      faq("How many steps should I use?", "8–12 steps cover most UI spacing needs."),
    ],
    commonUseCases: ["Define design token spacing", "Create Tailwind-style scales", "Standardize layout margins and padding"],
  }),
  buildLiveTool({
    id: "rem-to-px",
    slug: "rem-to-px",
    title: "REM to PX Converter",
    category,
    subcategory: "layout-tools",
    shortDescription: "Convert rem units to pixels at any base font size.",
    metaTitle: "REM to PX Converter - CSS Unit Conversion",
    metaDescription: "Convert rem to px using your base font size. Free REM to pixel converter for responsive CSS.",
    keywords: ["rem to px", "rem converter", "css rem to px"],
    relatedTools: ["px-to-rem", "spacing-scale-generator", "color-converter"],
    componentKey: "GenericDesignTool",
    schemaType: "Calculator",
    formula: "px = rem × base font size",
    explanation: "Convert rem values to pixels using a configurable root font size (default 16px).",
    howToUse: ["Enter rem value.", "Set root font size if not 16px.", "View pixel equivalent."],
    examples: [{ title: "1.5rem at 16px root", input: "1.5 rem", output: "24 px", explanation: "1.5 × 16 = 24 pixels." }],
    faqs: [
      faq("Why is base font size important?", "Browsers default to 16px, but your site may override html font-size."),
      faq("Can I convert multiple values?", "Convert one value at a time or use spacing scale generator for lists."),
      faq("Is this for font-size only?", "Works for any CSS property using rem units."),
    ],
    commonUseCases: ["Communicate sizes to designers in px", "Verify responsive typography", "Convert rem spacing to px specs"],
  }),
  buildLiveTool({
    id: "px-to-rem",
    slug: "px-to-rem",
    title: "PX to REM Converter",
    category,
    subcategory: "layout-tools",
    shortDescription: "Convert pixel values to rem for responsive CSS.",
    metaTitle: "PX to REM Converter - CSS Unit Conversion",
    metaDescription: "Convert px to rem using your base font size. Free pixel to REM converter for responsive design.",
    keywords: ["px to rem", "pixel to rem", "css px to rem"],
    relatedTools: ["rem-to-px", "spacing-scale-generator", "color-converter"],
    componentKey: "GenericDesignTool",
    schemaType: "Calculator",
    formula: "rem = px ÷ base font size",
    explanation: "Convert pixel values to rem using a configurable root font size (default 16px).",
    howToUse: ["Enter pixel value.", "Set root font size if not 16px.", "View rem equivalent."],
    examples: [{ title: "24px at 16px root", input: "24 px", output: "1.5 rem", explanation: "24 ÷ 16 = 1.5 rem." }],
    faqs: [
      faq("Why use rem over px?", "Rem scales with user font preferences for better accessibility."),
      faq("What root size should I use?", "16px is the browser default; match your project's html font-size."),
      faq("Can I convert decimal px?", "Yes. Enter values like 18.5 px."),
    ],
    commonUseCases: ["Build accessible CSS", "Convert design specs to rem", "Create scalable component spacing"],
  }),
];
