import type { ToolDefinition } from "./types";
import { buildUnitConverterTool, type UnitPairMeta } from "./registry-live-converters-pairs";

const pair = (meta: UnitPairMeta): ToolDefinition => buildUnitConverterTool(meta);

export const expandedUnitPairTools2: ToolDefinition[] = [
  pair({
    id: "square-meters-to-acres",
    slug: "square-meters-to-acres",
    title: "Square Meters to Acres Converter",
    subcategory: "area",
    shortDescription: "Convert square meters to acres for land area comparisons.",
    metaTitle: "Square Meters to Acres Converter - Free Area Conversion",
    metaDescription: "Convert square meters to acres instantly. Uses 1 acre = 4,046.86 m² with formula and reverse link.",
    keywords: ["square meters to acres", "sq m to acres", "m2 to acres"],
    formula: "acres = square meters ÷ 4,046.8564224",
    explanation: "Convert metric land area from square meters to US customary acres.",
    exampleTitle: "4,047 square meters",
    exampleInput: "4047",
    exampleOutput: "1",
    exampleExplanation: "4,047 ÷ 4,046.8564224 ≈ 1 acre.",
    reverseId: "acres-to-square-meters",
    relatedTools: ["square-meters-to-square-feet", "acres-to-square-feet", "hectares-to-acres"],
    sourceNote: "1 acre = 4,046.8564224 square meters.",
  }),
  pair({
    id: "acres-to-square-meters",
    slug: "acres-to-square-meters",
    title: "Acres to Square Meters Converter",
    subcategory: "area",
    shortDescription: "Convert acres to square meters for metric land area.",
    metaTitle: "Acres to Square Meters Converter - Free Area Conversion",
    metaDescription: "Convert acres to square meters instantly. Uses m² = acres × 4,046.86 with formula and reverse link.",
    keywords: ["acres to square meters", "acres to sq m"],
    formula: "square meters = acres × 4,046.8564224",
    explanation: "Convert US customary acres to metric square meters.",
    exampleTitle: "2 acres",
    exampleInput: "2",
    exampleOutput: "8,093.713",
    exampleExplanation: "2 × 4,046.8564224 ≈ 8,093.71 square meters.",
    reverseId: "square-meters-to-acres",
    relatedTools: ["square-feet-to-square-meters", "acres-to-square-feet", "hectares-to-acres"],
    sourceNote: "1 acre = 4,046.8564224 square meters.",
  }),
  pair({
    id: "mm-to-cm",
    slug: "mm-to-cm",
    title: "MM to CM Converter",
    subcategory: "length",
    shortDescription: "Convert millimeters to centimeters instantly.",
    metaTitle: "MM to CM Converter - Millimeters to Centimeters",
    metaDescription: "Convert millimeters to centimeters online. Uses 1 cm = 10 mm with examples and reverse link.",
    keywords: ["mm to cm", "millimeters to centimeters"],
    formula: "centimeters = millimeters ÷ 10",
    explanation: "Convert millimeters to centimeters within the metric system.",
    exampleTitle: "100 millimeters",
    exampleInput: "100",
    exampleOutput: "10",
    exampleExplanation: "100 ÷ 10 = 10 centimeters.",
    reverseId: "cm-to-mm",
    relatedTools: ["mm-to-inches", "cm-to-inches", "meters-to-feet"],
    sourceNote: "1 centimeter = 10 millimeters.",
  }),
  pair({
    id: "cm-to-mm",
    slug: "cm-to-mm",
    title: "CM to MM Converter",
    subcategory: "length",
    shortDescription: "Convert centimeters to millimeters instantly.",
    metaTitle: "CM to MM Converter - Centimeters to Millimeters",
    metaDescription: "Convert centimeters to millimeters online. Uses mm = cm × 10 with examples and reverse link.",
    keywords: ["cm to mm", "centimeters to millimeters"],
    formula: "millimeters = centimeters × 10",
    explanation: "Convert centimeters to millimeters within the metric system.",
    exampleTitle: "10 centimeters",
    exampleInput: "10",
    exampleOutput: "100",
    exampleExplanation: "10 × 10 = 100 millimeters.",
    reverseId: "mm-to-cm",
    relatedTools: ["inches-to-cm", "mm-to-inches", "meters-to-feet"],
    sourceNote: "1 centimeter = 10 millimeters.",
  }),
  pair({
    id: "stones-to-kg",
    slug: "stones-to-kg",
    title: "Stones to KG Converter",
    subcategory: "weight",
    shortDescription: "Convert stones to kilograms for body weight.",
    metaTitle: "Stones to KG Converter - Stone to Kilograms",
    metaDescription: "Convert stones to kilograms instantly. Uses 1 stone = 6.35029 kg with examples and reverse link.",
    keywords: ["stones to kg", "stone to kilograms", "st to kg"],
    formula: "kilograms = stones × 6.35029318",
    explanation: "Convert UK stone weight to metric kilograms.",
    exampleTitle: "10 stones",
    exampleInput: "10",
    exampleOutput: "63.502932",
    exampleExplanation: "10 × 6.35029318 ≈ 63.50 kilograms.",
    reverseId: "kg-to-stones",
    relatedTools: ["kg-to-lbs", "lbs-to-kg", "ounces-to-grams"],
    sourceNote: "1 stone = 14 pounds = 6.35029318 kilograms.",
  }),
  pair({
    id: "kg-to-stones",
    slug: "kg-to-stones",
    title: "KG to Stones Converter",
    subcategory: "weight",
    shortDescription: "Convert kilograms to stones for UK body weight.",
    metaTitle: "KG to Stones Converter - Kilograms to Stone",
    metaDescription: "Convert kilograms to stones instantly. Uses stones = kg ÷ 6.35029 with examples and reverse link.",
    keywords: ["kg to stones", "kilograms to stone"],
    formula: "stones = kilograms ÷ 6.35029318",
    explanation: "Convert metric kilograms to UK stones.",
    exampleTitle: "63.5 kilograms",
    exampleInput: "63.5",
    exampleOutput: "10",
    exampleExplanation: "63.5 ÷ 6.35029318 ≈ 10 stones.",
    reverseId: "stones-to-kg",
    relatedTools: ["kg-to-lbs", "lbs-to-kg", "grams-to-ounces"],
    sourceNote: "1 stone = 6.35029318 kilograms.",
  }),
  pair({
    id: "cups-to-ml",
    slug: "cups-to-ml",
    title: "Cups to ML Converter",
    subcategory: "volume",
    shortDescription: "Convert US cups to milliliters for recipes and liquids.",
    metaTitle: "Cups to ML Converter - US Cups to Milliliters",
    metaDescription: "Convert US cups to milliliters instantly. Uses 1 cup = 236.588 ml with examples and reverse link.",
    keywords: ["cups to ml", "cup to milliliters", "cups to milliliters"],
    formula: "milliliters = US cups × 236.588236",
    explanation: "Convert US customary cups to metric milliliters.",
    exampleTitle: "2 US cups",
    exampleInput: "2",
    exampleOutput: "473.176472",
    exampleExplanation: "2 × 236.588236 ≈ 473.18 milliliters.",
    reverseId: "ml-to-cups",
    relatedTools: ["liters-to-gallons", "tablespoon-to-ml", "recipe-scaler"],
    sourceNote: "1 US cup = 236.588236 milliliters.",
  }),
  pair({
    id: "ml-to-cups",
    slug: "ml-to-cups",
    title: "ML to Cups Converter",
    subcategory: "volume",
    shortDescription: "Convert milliliters to US cups for recipes.",
    metaTitle: "ML to Cups Converter - Milliliters to US Cups",
    metaDescription: "Convert milliliters to US cups instantly. Uses cups = ml ÷ 236.588 with examples and reverse link.",
    keywords: ["ml to cups", "milliliters to cups"],
    formula: "US cups = milliliters ÷ 236.588236",
    explanation: "Convert metric milliliters to US customary cups.",
    exampleTitle: "473 milliliters",
    exampleInput: "473",
    exampleOutput: "1.999",
    exampleExplanation: "473 ÷ 236.588236 ≈ 2 cups.",
    reverseId: "cups-to-ml",
    relatedTools: ["liters-to-gallons", "cups-to-grams", "recipe-scaler"],
    sourceNote: "1 US cup = 236.588236 milliliters.",
  }),
  pair({
    id: "bytes-to-kb",
    slug: "bytes-to-kb",
    title: "Bytes to KB Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert bytes to kilobytes using binary (1024-based) units.",
    metaTitle: "Bytes to KB Converter - Bytes to Kilobytes",
    metaDescription: "Convert bytes to kilobytes instantly. Uses binary division by 1024 with examples and reverse link.",
    keywords: ["bytes to kb", "bytes to kilobytes"],
    formula: "kilobytes = bytes ÷ 1024",
    explanation: "Convert digital storage from bytes to binary kilobytes.",
    exampleTitle: "2048 bytes",
    exampleInput: "2048",
    exampleOutput: "2",
    exampleExplanation: "2048 ÷ 1024 = 2 kilobytes.",
    reverseId: "kb-to-bytes",
    relatedTools: ["kb-to-mb", "mb-to-gb", "bits-to-bytes"],
    sourceNote: "Binary: 1 kilobyte = 1024 bytes.",
  }),
  pair({
    id: "kb-to-bytes",
    slug: "kb-to-bytes",
    title: "KB to Bytes Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert kilobytes to bytes using binary (1024-based) units.",
    metaTitle: "KB to Bytes Converter - Kilobytes to Bytes",
    metaDescription: "Convert kilobytes to bytes instantly. Uses binary multiplication by 1024 with examples.",
    keywords: ["kb to bytes", "kilobytes to bytes"],
    formula: "bytes = kilobytes × 1024",
    explanation: "Convert binary kilobytes to bytes.",
    exampleTitle: "2 kilobytes",
    exampleInput: "2",
    exampleOutput: "2,048",
    exampleExplanation: "2 × 1024 = 2,048 bytes.",
    reverseId: "bytes-to-kb",
    relatedTools: ["kb-to-mb", "bytes-to-bits", "mb-to-kb"],
    sourceNote: "Binary: 1 kilobyte = 1024 bytes.",
  }),
  pair({
    id: "bits-to-bytes",
    slug: "bits-to-bytes",
    title: "Bits to Bytes Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert bits to bytes for data size calculations.",
    metaTitle: "Bits to Bytes Converter - Convert Bits to Bytes",
    metaDescription: "Convert bits to bytes instantly. Uses 1 byte = 8 bits with examples and reverse link.",
    keywords: ["bits to bytes", "bit to byte converter"],
    formula: "bytes = bits ÷ 8",
    explanation: "Convert bit counts to byte counts using 8 bits per byte.",
    exampleTitle: "64 bits",
    exampleInput: "64",
    exampleOutput: "8",
    exampleExplanation: "64 ÷ 8 = 8 bytes.",
    reverseId: "bytes-to-bits",
    relatedTools: ["bytes-to-kb", "kb-to-mb", "mb-to-gb"],
    sourceNote: "1 byte = 8 bits.",
  }),
  pair({
    id: "bytes-to-bits",
    slug: "bytes-to-bits",
    title: "Bytes to Bits Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert bytes to bits for low-level data sizing.",
    metaTitle: "Bytes to Bits Converter - Convert Bytes to Bits",
    metaDescription: "Convert bytes to bits instantly. Uses bits = bytes × 8 with examples and reverse link.",
    keywords: ["bytes to bits", "byte to bit converter"],
    formula: "bits = bytes × 8",
    explanation: "Convert byte counts to bit counts using 8 bits per byte.",
    exampleTitle: "1 byte",
    exampleInput: "1",
    exampleOutput: "8",
    exampleExplanation: "1 × 8 = 8 bits.",
    reverseId: "bits-to-bytes",
    relatedTools: ["bytes-to-kb", "kb-to-mb", "bits-to-bytes"],
    sourceNote: "1 byte = 8 bits.",
  }),
  pair({
    id: "board-feet-to-cubic-feet",
    slug: "board-feet-to-cubic-feet",
    title: "Board Feet to Cubic Feet Converter",
    subcategory: "volume",
    shortDescription: "Convert lumber board feet to cubic feet volume.",
    metaTitle: "Board Feet to Cubic Feet Converter - Lumber Volume",
    metaDescription: "Convert board feet to cubic feet instantly. Uses 1 board foot = 1/12 cubic foot with lumber examples.",
    keywords: ["board feet to cubic feet", "board foot to cu ft"],
    formula: "cubic feet = board feet ÷ 12",
    explanation: "Convert lumber board feet to cubic feet using the standard board-foot definition.",
    exampleTitle: "12 board feet",
    exampleInput: "12",
    exampleOutput: "1",
    exampleExplanation: "12 ÷ 12 = 1 cubic foot.",
    reverseId: "cubic-feet-to-board-feet",
    relatedTools: ["lumber-calculator", "cubic-feet-to-cubic-yards", "cubic-yards-to-cubic-feet"],
    sourceNote: "1 board foot = 1 ft × 1 ft × 1 in = 1/12 cubic foot.",
  }),
  pair({
    id: "cubic-feet-to-board-feet",
    slug: "cubic-feet-to-board-feet",
    title: "Cubic Feet to Board Feet Converter",
    subcategory: "volume",
    shortDescription: "Convert cubic feet volume to lumber board feet.",
    metaTitle: "Cubic Feet to Board Feet Converter - Lumber Volume",
    metaDescription: "Convert cubic feet to board feet instantly. Uses board feet = cu ft × 12 with lumber examples.",
    keywords: ["cubic feet to board feet", "cu ft to board foot"],
    formula: "board feet = cubic feet × 12",
    explanation: "Convert cubic feet to board feet for lumber volume estimates.",
    exampleTitle: "1 cubic foot",
    exampleInput: "1",
    exampleOutput: "12",
    exampleExplanation: "1 × 12 = 12 board feet.",
    reverseId: "board-feet-to-cubic-feet",
    relatedTools: ["lumber-calculator", "cubic-feet-to-cubic-yards"],
    sourceNote: "1 cubic foot = 12 board feet by definition.",
  }),
];
