import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "kitchen-recipe-tools";

export const kitchenLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "recipe-scaler",
    slug: "recipe-scaler",
    title: "Recipe Scaler",
    category,
    subcategory: "recipe-scaling",
    shortDescription: "Scale recipe ingredients up or down by servings.",
    metaTitle: "Recipe Scaler - Scale Ingredients by Servings",
    metaDescription: "Scale recipe ingredient quantities up or down by changing serving counts. Free recipe scaler online.",
    keywords: ["recipe scaler", "scale recipe", "recipe multiplier"],
    relatedTools: ["serving-calculator", "cups-to-grams", "ingredient-converter"],
    componentKey: "GenericKitchenTool",
    explanation: "Paste ingredient lines with leading quantities and scale to a new serving count.",
    howToUse: ["Paste ingredients with quantities at the start of each line.", "Enter original and target servings.", "Copy scaled ingredient list."],
    examples: [{ title: "Double a 4-serving recipe", input: "4 servings → 8 servings", output: "All quantities × 2", explanation: "Scale factor = target ÷ original = 2." }],
    faqs: [
      faq("What format should ingredients use?", "Start each line with a number, such as '2 cups flour'."),
      faq("Does it scale fractions?", "Whole and decimal numbers scale; complex fractions may need manual review."),
      faq("Can I scale baking recipes?", "Yes, but leavening agents sometimes need slight adjustment beyond linear scaling."),
    ],
    commonUseCases: ["Cook for larger groups", "Halve recipes for two people", "Adjust catering batch sizes"],
    assumptions: ["Linear scaling works for most ingredients.", "Leavening and seasoning may need taste adjustment."],
    sourceNotes: ["USDA and common cookbook scaling practices use proportional ingredient multiplication."],
  }),
  buildLiveTool({
    id: "cups-to-grams",
    slug: "cups-to-grams",
    title: "Cups to Grams Converter",
    category,
    subcategory: "measurement-conversion",
    shortDescription: "Convert cup measurements to grams by ingredient.",
    metaTitle: "Cups to Grams Converter - Baking Conversion",
    metaDescription: "Convert cups to grams by common baking ingredients. Free cups to grams converter for recipes.",
    keywords: ["cups to grams", "cup to gram converter", "baking conversion"],
    relatedTools: ["tbsp-to-ml", "ingredient-converter", "recipe-scaler"],
    componentKey: "GenericKitchenTool",
    schemaType: "Calculator",
    formula: "grams = cups × ingredient density (g per cup)",
    explanation: "Estimate grams from cups using common ingredient density values.",
    howToUse: ["Select an ingredient.", "Enter number of cups.", "View estimated grams."],
    examples: [{ title: "2 cups all-purpose flour", input: "2 cups flour", output: "≈ 240 g", explanation: "Uses ~120 g per cup for all-purpose flour." }],
    faqs: [
      faq("Why do grams vary by ingredient?", "Density differs—flour, sugar, and butter weigh different amounts per cup."),
      faq("Is this exact?", "These are common estimates; sifted vs packed cups can vary."),
      faq("Can I use metric cups?", "Values assume US customary cups (236.588 ml)."),
    ],
    commonUseCases: ["Convert US recipes to metric baking", "Weigh ingredients for accuracy", "Scale baking recipes precisely"],
    sourceNotes: ["USDA FoodData Central and King Arthur Baking reference densities."],
  }),
  buildLiveTool({
    id: "tbsp-to-ml",
    slug: "tbsp-to-ml",
    title: "Tablespoon to ML Converter",
    category,
    subcategory: "measurement-conversion",
    shortDescription: "Convert tablespoons to milliliters.",
    metaTitle: "Tablespoon to ML Converter - Volume Conversion",
    metaDescription: "Convert tablespoons to milliliters instantly. Free tbsp to ml converter for cooking and baking.",
    keywords: ["tbsp to ml", "tablespoon to ml", "tablespoon converter"],
    relatedTools: ["cups-to-grams", "ingredient-converter", "oven-temp-converter"],
    componentKey: "GenericKitchenTool",
    schemaType: "Calculator",
    formula: "1 US tbsp = 14.7868 ml",
    explanation: "Convert tablespoon measurements to milliliters using standard US volume conversion.",
    howToUse: ["Enter tablespoons.", "View milliliters instantly."],
    examples: [{ title: "3 tablespoons", input: "3 tbsp", output: "44.36 ml", explanation: "3 × 14.7868 ≈ 44.36 ml." }],
    faqs: [
      faq("US or UK tablespoon?", "US customary tablespoon (14.7868 ml). UK tablespoons differ."),
      faq("Can I convert ml back?", "Use the ingredient converter for ml to tbsp."),
      faq("Is this for liquid only?", "Volume conversion applies to liquids; dry tbsp measures may vary by ingredient."),
    ],
    commonUseCases: ["Follow European recipes", "Measure liquid seasonings", "Convert sauce quantities"],
    sourceNotes: ["NIST: 1 US tablespoon = 14.7867647825 ml."],
  }),
  buildLiveTool({
    id: "oven-temp-converter",
    slug: "oven-temp-converter",
    title: "Oven Temperature Converter",
    category,
    subcategory: "measurement-conversion",
    shortDescription: "Convert Fahrenheit and Celsius oven temperatures.",
    metaTitle: "Oven Temperature Converter - F to C and C to F",
    metaDescription: "Convert oven temperatures between Fahrenheit and Celsius. Free oven temp converter for recipes.",
    keywords: ["oven temperature converter", "fahrenheit to celsius oven", "baking temperature converter"],
    relatedTools: ["tbsp-to-ml", "cups-to-grams", "celsius-to-fahrenheit"],
    componentKey: "GenericKitchenTool",
    schemaType: "Calculator",
    formula: "°C = (°F − 32) × 5/9; °F = (°C × 9/5) + 32",
    explanation: "Convert oven baking temperatures between Fahrenheit and Celsius.",
    howToUse: ["Enter temperature in °F or °C.", "View the converted oven temperature."],
    examples: [{ title: "350°F oven", input: "350°F", output: "177°C", explanation: "Common US baking temperature converted to Celsius." }],
    faqs: [
      faq("Should I adjust cooking time?", "Fan ovens and altitude may require time adjustments beyond temperature conversion."),
      faq("What about gas mark?", "This tool converts °F and °C only."),
      faq("Are values rounded?", "Results show practical oven-setting values."),
    ],
    commonUseCases: ["Use US recipes in metric ovens", "Convert UK/EU recipes to Fahrenheit", "Set oven dial correctly"],
  }),
  buildLiveTool({
    id: "serving-calculator",
    slug: "serving-calculator",
    title: "Serving Size Calculator",
    category,
    subcategory: "portion-planning",
    shortDescription: "Calculate recipe scale multiplier for guest count.",
    metaTitle: "Serving Size Calculator - Scale for Guests",
    metaDescription: "Calculate how much to scale a recipe for a guest count. Free serving size calculator for events.",
    keywords: ["serving calculator", "portion calculator", "recipe servings"],
    relatedTools: ["recipe-scaler", "ingredient-converter", "cups-to-grams"],
    componentKey: "GenericKitchenTool",
    formula: "multiplier = target servings ÷ original servings",
    explanation: "Find the multiplier needed to adjust a recipe from its original servings to your guest count.",
    howToUse: ["Enter original recipe servings.", "Enter target guest count.", "View scale multiplier."],
    examples: [{ title: "Recipe for 6, need 15 guests", input: "6 → 15 servings", output: "multiplier 2.5×", explanation: "15 ÷ 6 = 2.5; multiply all ingredients by 2.5." }],
    faqs: [
      faq("How is this different from recipe scaler?", "This shows the multiplier; recipe scaler applies it to ingredient lines."),
      faq("Can I round the multiplier?", "Round ingredient amounts sensibly after scaling."),
      faq("Does it account for leftovers?", "Add extra servings to your target count if desired."),
    ],
    commonUseCases: ["Plan dinner party portions", "Scale meal prep batches", "Calculate catering quantities"],
  }),
  buildLiveTool({
    id: "ingredient-converter",
    slug: "ingredient-converter",
    title: "Ingredient Unit Converter",
    category,
    subcategory: "portion-planning",
    shortDescription: "Convert common cooking volume units.",
    metaTitle: "Ingredient Unit Converter - Cooking Units",
    metaDescription: "Convert tsp, tbsp, cups, and ml for cooking measurements. Free ingredient unit converter.",
    keywords: ["ingredient converter", "cooking unit converter", "recipe unit conversion"],
    relatedTools: ["cups-to-grams", "tbsp-to-ml", "recipe-scaler"],
    componentKey: "GenericKitchenTool",
    explanation: "Convert between teaspoon, tablespoon, cup, and milliliter measurements.",
    howToUse: ["Select from and to units.", "Enter quantity.", "View converted amount."],
    examples: [{ title: "1 cup to tablespoons", input: "1 cup", output: "16 tbsp", explanation: "1 US cup = 16 US tablespoons." }],
    faqs: [
      faq("Which cup measure is used?", "US customary cup (236.588 ml)."),
      faq("Can I convert weight units?", "Use cups-to-grams for weight by ingredient."),
      faq("Are UK measures supported?", "This uses US customary cooking units."),
    ],
    commonUseCases: ["Substitute measuring spoons for cups", "Convert recipe units quickly", "Match tool measurements to recipe"],
    sourceNotes: ["1 cup = 16 tbsp = 48 tsp = 236.588 ml (US customary)."],
  }),
];
