import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "time-date-tools";

export const timeDateLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "timezone-converter",
    slug: "timezone-converter",
    title: "Time Zone Converter",
    category,
    subcategory: "time-zones",
    shortDescription: "Convert times between global IANA time zones.",
    metaTitle: "Time Zone Converter - Convert Time Between Zones",
    metaDescription: "Convert date and time values between IANA time zones. Free time zone converter for meetings and scheduling.",
    keywords: ["timezone converter", "time zone converter", "convert time zones"],
    relatedTools: ["unix-timestamp", "date-difference", "countdown-calculator"],
    componentKey: "GenericTimeDateTool",
    explanation: "Format a date and time for a target IANA time zone such as America/New_York or Europe/London.",
    howToUse: ["Enter date and time.", "Select source and target time zones.", "View converted local time."],
    examples: [{ title: "NYC to London", input: "2026-06-01 14:00 America/New_York", output: "2026-06-01 19:00 Europe/London", explanation: "Accounts for time zone offset on the given date." }],
    faqs: [
      faq("Does it handle daylight saving time?", "Yes, when using IANA time zone names with DST rules."),
      faq("What format should I enter?", "Use the date/time fields provided in the tool."),
      faq("Can I convert UTC?", "Use Etc/UTC or select UTC-equivalent zones."),
    ],
    commonUseCases: ["Schedule international meetings", "Convert flight arrival times", "Plan webinar times for global audiences"],
  }),
  buildLiveTool({
    id: "age-calculator",
    slug: "age-calculator",
    title: "Age Calculator",
    category,
    subcategory: "date-calculators",
    shortDescription: "Calculate exact age from birth date.",
    metaTitle: "Age Calculator - Calculate Age from Birth Date",
    metaDescription: "Calculate exact age in years, months, and days from a birth date. Free age calculator online.",
    keywords: ["age calculator", "calculate age", "birth date age"],
    relatedTools: ["date-difference", "countdown-calculator", "business-days-calculator"],
    componentKey: "GenericTimeDateTool",
    schemaType: "Calculator",
    explanation: "Enter a birth date to see age in years, months, and days as of today or a chosen date.",
    howToUse: ["Enter birth date.", "Optionally set an as-of date.", "View age breakdown."],
    examples: [{ title: "Born Jan 1, 2000", input: "2000-01-01", output: "26 years (as of 2026)", explanation: "Calculates full years, months, and days elapsed." }],
    faqs: [
      faq("Does it account for leap years?", "Yes. Date math includes leap day handling."),
      faq("Can I calculate age on a past date?", "Set the as-of date to any reference point."),
      faq("What date format is used?", "Use the date picker or ISO-style date input."),
    ],
    commonUseCases: ["Verify eligibility by age", "Calculate child age in months", "Fill forms requiring exact age"],
  }),
  buildLiveTool({
    id: "date-difference",
    slug: "date-difference",
    title: "Date Difference Calculator",
    category,
    subcategory: "date-calculators",
    shortDescription: "Find days and hours between two dates.",
    metaTitle: "Date Difference Calculator - Days Between Dates",
    metaDescription: "Calculate the difference between two dates in days and hours. Free date duration calculator.",
    keywords: ["date difference calculator", "days between dates", "date duration"],
    relatedTools: ["business-days-calculator", "age-calculator", "countdown-calculator"],
    componentKey: "GenericTimeDateTool",
    schemaType: "Calculator",
    formula: "duration = end date − start date",
    explanation: "Measure elapsed time between a start date and end date in days and hours.",
    howToUse: ["Enter start date.", "Enter end date.", "View elapsed days and hours."],
    examples: [{ title: "Jan 1 to Jan 31", input: "2026-01-01 to 2026-01-31", output: "30 days", explanation: "Calendar day difference between dates." }],
    faqs: [
      faq("Are start and end dates inclusive?", "Duration is the difference between the two dates."),
      faq("Does it include time of day?", "If times are provided, hours are included in the result."),
      faq("Can end date be before start?", "Yes. Results show elapsed time in the forward direction."),
    ],
    commonUseCases: ["Calculate project duration", "Track days until deadline", "Measure rental or trial periods"],
  }),
  buildLiveTool({
    id: "unix-timestamp",
    slug: "unix-timestamp",
    title: "Unix Timestamp Converter",
    category,
    subcategory: "timestamps",
    shortDescription: "Convert Unix timestamps to readable dates and back.",
    metaTitle: "Unix Timestamp Converter - Epoch to Date",
    metaDescription: "Convert Unix timestamps to readable dates and dates to Unix epoch seconds. Free timestamp converter.",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date"],
    relatedTools: ["timezone-converter", "date-difference", "countdown-calculator"],
    componentKey: "GenericTimeDateTool",
    explanation: "Convert between Unix epoch seconds and human-readable date strings.",
    howToUse: ["Enter a Unix timestamp or pick a date.", "Switch between to-date and to-timestamp modes.", "Copy the converted value."],
    examples: [{ title: "Epoch zero", input: "0", output: "1970-01-01 00:00:00 UTC", explanation: "Unix epoch starts at 1970-01-01T00:00:00Z." }],
    faqs: [
      faq("Seconds or milliseconds?", "This tool uses Unix seconds; multiply milliseconds by 1000 if needed."),
      faq("What timezone is used?", "Timestamps convert relative to UTC unless a zone is specified."),
      faq("Can I get current timestamp?", "Use the current time button if available in the tool."),
    ],
    commonUseCases: ["Debug API responses", "Convert log timestamps", "Work with database epoch fields"],
    sourceNotes: ["Unix time: seconds since 1970-01-01 00:00:00 UTC."],
  }),
  buildLiveTool({
    id: "business-days-calculator",
    slug: "business-days-calculator",
    title: "Business Days Calculator",
    category,
    subcategory: "date-calculators",
    shortDescription: "Count business days between two dates.",
    metaTitle: "Business Days Calculator - Weekday Count",
    metaDescription: "Count business days (Mon–Fri) between two dates. Free business day calculator for deadlines and SLAs.",
    keywords: ["business days calculator", "working days calculator", "weekday count"],
    relatedTools: ["date-difference", "countdown-calculator", "age-calculator"],
    componentKey: "GenericTimeDateTool",
    schemaType: "Calculator",
    explanation: "Count weekdays between two dates, excluding Saturday and Sunday.",
    howToUse: ["Enter start and end dates.", "View count of Mon–Fri business days."],
    examples: [{ title: "Mon to Fri same week", input: "Mon–Fri (5 weekdays)", output: "5 business days", explanation: "Counts weekdays only, not calendar days." }],
    faqs: [
      faq("Are holidays excluded?", "No. Only weekends are excluded in this version."),
      faq("Is the start date included?", "Business days between dates follow the tool's counting rules."),
      faq("Can I count forward from today?", "Enter today as start and your deadline as end."),
    ],
    commonUseCases: ["Calculate SLA deadlines", "Estimate shipping business days", "Plan project timelines excluding weekends"],
    assumptions: ["Monday–Friday are business days.", "Public holidays are not excluded."],
  }),
  buildLiveTool({
    id: "countdown-calculator",
    slug: "countdown-calculator",
    title: "Countdown Calculator",
    category,
    subcategory: "countdowns",
    shortDescription: "Count down to a target date and time.",
    metaTitle: "Countdown Calculator - Time Until Event",
    metaDescription: "Calculate days, hours, and minutes until a target date or deadline. Free countdown calculator.",
    keywords: ["countdown calculator", "time until date", "event countdown"],
    relatedTools: ["date-difference", "age-calculator", "business-days-calculator"],
    componentKey: "GenericTimeDateTool",
    explanation: "See remaining or elapsed time until a target date and time.",
    howToUse: ["Enter target date and time.", "View days, hours, and minutes remaining."],
    examples: [{ title: "New Year's countdown", input: "Target: Jan 1 2027 00:00", output: "Days, hours, minutes remaining", explanation: "Updates based on current date/time." }],
    faqs: [
      faq("Does it update live?", "Recalculate by refreshing or changing the target date."),
      faq("What if the date is in the past?", "Shows elapsed time since the target."),
      faq("Can I include time of day?", "Yes. Enter both date and time for precision."),
    ],
    commonUseCases: ["Track launch dates", "Count down to events", "Monitor deadline remaining time"],
  }),
];
