import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";
import { expandedUnitPairTools } from "./registry-live-converters-pairs";
import { expandedUnitPairTools2 } from "./registry-live-converters-pairs-2";

const baseConverterTools: ToolDefinition[] = [
  buildLiveTool({
    id: "hectares-to-acres",
    slug: "hectares-to-acres",
    title: "Hectares to Acres Converter",
    category: "unit-converters",
    subcategory: "area",
    shortDescription: "Convert hectares to acres using standard land area conversion factors.",
    metaTitle: "Hectares to Acres Converter - Free Land Area Conversion",
    metaDescription:
      "Convert hectares to acres instantly. Uses metric-to-US customary area factors with examples, formula, and reverse conversion link.",
    keywords: ["hectares to acres", "hectare to acre", "ha to acres"],
    relatedTools: ["acres-to-hectares", "acres-to-square-feet", "square-feet-to-acres"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "acres = hectares × (107,639.104 ÷ 43,560)",
    explanation:
      "Convert land area from hectares to acres using square-foot equivalence between metric and US customary units.",
    howToUse: [
      "Enter the number of hectares.",
      "View the acres result instantly.",
      "Use the reverse converter link for acres to hectares.",
    ],
    examples: [
      {
        title: "10 hectares",
        input: "10",
        output: "24.710538",
        explanation: "10 × (107,639.104 ÷ 43,560) ≈ 24.71 acres.",
      },
    ],
    faqs: [
      faq("How many acres are in one hectare?", "One hectare equals about 2.471 acres using standard conversion factors."),
      faq("Can I convert acres back to hectares?", "Yes. Use the Acres to Hectares converter."),
      faq("Is this the same as square feet conversion?", "Hectares and acres are area units; use square feet converters for ft² totals."),
    ],
    commonUseCases: [
      "Compare international land listings",
      "Convert farm or ranch acreage from metric surveys",
      "Estimate parcel size for US listings",
    ],
    sourceNotes: [
      "One hectare = 10,000 m² = 107,639.104 square feet.",
      "One acre = 43,560 square feet (US customary definition).",
    ],
  }),
  buildLiveTool({
    id: "acres-to-hectares",
    slug: "acres-to-hectares",
    title: "Acres to Hectares Converter",
    category: "unit-converters",
    subcategory: "area",
    shortDescription: "Convert acres to hectares for metric land area measurements.",
    metaTitle: "Acres to Hectares Converter - Free Land Area Conversion",
    metaDescription:
      "Convert acres to hectares instantly. Uses US customary-to-metric area factors with formula, examples, and reverse conversion link.",
    keywords: ["acres to hectares", "acre to hectare", "acres to ha"],
    relatedTools: ["hectares-to-acres", "acres-to-square-feet", "square-feet-to-acres"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "hectares = acres × (43,560 ÷ 107,639.104)",
    explanation:
      "Convert land area from acres to hectares using the standard square-foot equivalence between US and metric units.",
    howToUse: [
      "Enter the number of acres.",
      "View the hectares result instantly.",
      "Use the reverse converter link for hectares to acres.",
    ],
    examples: [
      {
        title: "25 acres",
        input: "25",
        output: "10.117141",
        explanation: "25 × (43,560 ÷ 107,639.104) ≈ 10.12 hectares.",
      },
    ],
    faqs: [
      faq("How many hectares are in one acre?", "One acre equals about 0.4047 hectares."),
      faq("Can I enter decimal acre values?", "Yes. Decimal acreage is supported."),
      faq("Does this use US survey acres?", "This tool uses the standard 43,560 square foot acre definition."),
    ],
    commonUseCases: [
      "Convert US property listings to metric area",
      "Prepare international land reports",
      "Compare ranch sizes across countries",
    ],
    sourceNotes: [
      "One acre = 43,560 square feet.",
      "One hectare = 107,639.104 square feet.",
    ],
  }),
  buildLiveTool({
    id: "meters-to-feet",
    slug: "meters-to-feet",
    title: "Meters to Feet Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert meters to feet for length, height, and distance measurements.",
    metaTitle: "Meters to Feet Converter - Free Length Conversion",
    metaDescription:
      "Convert meters to feet instantly. Uses 1 meter = 3.280839895 feet with examples, formula, and reverse conversion link.",
    keywords: ["meters to feet", "m to ft", "metres to feet"],
    relatedTools: ["feet-to-meters", "miles-to-km", "km-to-miles"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "feet = meters × 3.280839895",
    explanation: "Convert metric length from meters to US customary feet.",
    howToUse: [
      "Enter the length in meters.",
      "View the feet result instantly.",
      "Use the reverse converter link for feet to meters.",
    ],
    examples: [
      {
        title: "100 meters",
        input: "100",
        output: "328.08399",
        explanation: "100 × 3.280839895 ≈ 328.08 feet.",
      },
    ],
    faqs: [
      faq("Is this an exact conversion?", "It uses the standard international foot definition relative to the meter."),
      faq("Can I convert feet back to meters?", "Yes. Use the Feet to Meters converter."),
      faq("Does this support decimals?", "Yes. Decimal meter values are supported."),
    ],
    commonUseCases: [
      "Convert room dimensions for US listings",
      "Translate track or field measurements",
      "Convert building heights from metric plans",
    ],
    sourceNotes: ["Conversion factor: 1 meter = 3.280839895 feet (international foot)."],
  }),
  buildLiveTool({
    id: "feet-to-meters",
    slug: "feet-to-meters",
    title: "Feet to Meters Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert feet to meters for metric length measurements.",
    metaTitle: "Feet to Meters Converter - Free Length Conversion",
    metaDescription:
      "Convert feet to meters instantly. Uses feet ÷ 3.280839895 with examples, formula, and reverse conversion link.",
    keywords: ["feet to meters", "ft to m", "foot to meter"],
    relatedTools: ["meters-to-feet", "miles-to-km", "km-to-miles"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "meters = feet ÷ 3.280839895",
    explanation: "Convert US customary length from feet to metric meters.",
    howToUse: [
      "Enter the length in feet.",
      "View the meters result instantly.",
      "Use the reverse converter link for meters to feet.",
    ],
    examples: [
      {
        title: "328 feet",
        input: "328",
        output: "100",
        explanation: "328 ÷ 3.280839895 ≈ 100 meters.",
      },
    ],
    faqs: [
      faq("Can I enter decimal feet?", "Yes. Decimal foot values are supported."),
      faq("How do I convert meters to feet?", "Use the Meters to Feet converter."),
      faq("Is this for US or imperial feet?", "This uses the international foot equal to 0.3048 meters."),
    ],
    commonUseCases: [
      "Convert US floor plans to metric",
      "Translate height limits for international specs",
      "Prepare engineering dimensions in meters",
    ],
    sourceNotes: ["Conversion factor: 1 foot = 0.3048 meters; 1 meter = 3.280839895 feet."],
  }),
  buildLiveTool({
    id: "miles-to-km",
    slug: "miles-to-km",
    title: "Miles to Kilometers Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert miles to kilometers for travel, running, and map distances.",
    metaTitle: "Miles to Kilometers Converter - Free Distance Conversion",
    metaDescription:
      "Convert miles to kilometers instantly. Uses 1 mile = 1.609344 km with examples, formula, and reverse conversion link.",
    keywords: ["miles to km", "miles to kilometers", "mi to km"],
    relatedTools: ["km-to-miles", "meters-to-feet", "feet-to-meters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "kilometers = miles × 1.609344",
    explanation: "Convert US and UK road distances from miles to metric kilometers.",
    howToUse: [
      "Enter the distance in miles.",
      "View the kilometers result instantly.",
      "Use the reverse converter link for km to miles.",
    ],
    examples: [
      {
        title: "5 miles",
        input: "5",
        output: "8.04672",
        explanation: "5 × 1.609344 = 8.04672 kilometers.",
      },
    ],
    faqs: [
      faq("Is this the standard mile definition?", "Yes. It uses the international mile of exactly 1.609344 kilometers."),
      faq("Can I convert km back to miles?", "Yes. Use the Kilometers to Miles converter."),
      faq("Does this work for running distances?", "Yes. Enter race or training miles to get kilometers."),
    ],
    commonUseCases: [
      "Convert road trip distances for metric maps",
      "Translate running or cycling routes",
      "Compare speed limits across countries",
    ],
    sourceNotes: ["Conversion factor: 1 international mile = 1.609344 kilometers."],
  }),
  buildLiveTool({
    id: "km-to-miles",
    slug: "km-to-miles",
    title: "Kilometers to Miles Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert kilometers to miles for travel and fitness distances.",
    metaTitle: "Kilometers to Miles Converter - Free Distance Conversion",
    metaDescription:
      "Convert kilometers to miles instantly. Uses miles = km ÷ 1.609344 with examples, formula, and reverse conversion link.",
    keywords: ["km to miles", "kilometers to miles", "km to mi"],
    relatedTools: ["miles-to-km", "meters-to-feet", "feet-to-meters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "miles = kilometers ÷ 1.609344",
    explanation: "Convert metric distances from kilometers to miles.",
    howToUse: [
      "Enter the distance in kilometers.",
      "View the miles result instantly.",
      "Use the reverse converter link for miles to km.",
    ],
    examples: [
      {
        title: "10 kilometers",
        input: "10",
        output: "6.213712",
        explanation: "10 ÷ 1.609344 ≈ 6.21 miles.",
      },
    ],
    faqs: [
      faq("Can I enter decimal kilometers?", "Yes. Decimal kilometer values are supported."),
      faq("How do I convert miles to km?", "Use the Miles to Kilometers converter."),
      faq("Is this suitable for marathon distances?", "Yes. Enter race kilometers to get equivalent miles."),
    ],
    commonUseCases: [
      "Convert metric map routes to miles",
      "Translate race distances for US audiences",
      "Estimate travel distances on US road signs",
    ],
    sourceNotes: ["Conversion factor: 1 kilometer = 0.621371192 miles (1 ÷ 1.609344)."],
  }),
  buildLiveTool({
    id: "kg-to-lbs",
    slug: "kg-to-lbs",
    title: "Kilograms to Pounds Converter",
    category: "unit-converters",
    subcategory: "weight",
    shortDescription: "Convert kilograms to pounds for body weight and shipping.",
    metaTitle: "Kilograms to Pounds Converter - Free Weight Conversion",
    metaDescription:
      "Convert kg to lbs instantly. Uses 1 kilogram = 2.2046226218 pounds with examples, formula, and reverse conversion link.",
    keywords: ["kg to lbs", "kilograms to pounds", "kg to pounds"],
    relatedTools: ["lbs-to-kg", "liters-to-gallons", "gallons-to-liters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "pounds = kilograms × 2.2046226218",
    explanation: "Convert metric mass from kilograms to US customary pounds.",
    howToUse: [
      "Enter the weight in kilograms.",
      "View the pounds result instantly.",
      "Use the reverse converter link for lbs to kg.",
    ],
    examples: [
      {
        title: "70 kilograms",
        input: "70",
        output: "154.323584",
        explanation: "70 × 2.2046226218 ≈ 154.32 pounds.",
      },
    ],
    faqs: [
      faq("Is this an avoirdupois pound?", "Yes. It uses the standard international avoirdupois pound."),
      faq("Can I convert pounds back to kg?", "Yes. Use the Pounds to Kilograms converter."),
      faq("Does this support decimals?", "Yes. Decimal kilogram values are supported."),
    ],
    commonUseCases: [
      "Convert body weight for US charts",
      "Translate gym or sports weight limits",
      "Convert package weights for shipping labels",
    ],
    sourceNotes: ["Conversion factor: 1 kilogram = 2.2046226218 pounds (international avoirdupois)."],
  }),
  buildLiveTool({
    id: "lbs-to-kg",
    slug: "lbs-to-kg",
    title: "Pounds to Kilograms Converter",
    category: "unit-converters",
    subcategory: "weight",
    shortDescription: "Convert pounds to kilograms for metric weight measurements.",
    metaTitle: "Pounds to Kilograms Converter - Free Weight Conversion",
    metaDescription:
      "Convert lbs to kg instantly. Uses kilograms = pounds ÷ 2.2046226218 with examples, formula, and reverse conversion link.",
    keywords: ["lbs to kg", "pounds to kilograms", "lb to kg"],
    relatedTools: ["kg-to-lbs", "liters-to-gallons", "gallons-to-liters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "kilograms = pounds ÷ 2.2046226218",
    explanation: "Convert US customary weight from pounds to metric kilograms.",
    howToUse: [
      "Enter the weight in pounds.",
      "View the kilograms result instantly.",
      "Use the reverse converter link for kg to lbs.",
    ],
    examples: [
      {
        title: "150 pounds",
        input: "150",
        output: "68.038856",
        explanation: "150 ÷ 2.2046226218 ≈ 68.04 kilograms.",
      },
    ],
    faqs: [
      faq("Can I enter decimal pounds?", "Yes. Decimal pound values are supported."),
      faq("How do I convert kg to lbs?", "Use the Kilograms to Pounds converter."),
      faq("Is this for body weight and packages?", "Yes. The same pound-to-kilogram factor applies to mass measurements."),
    ],
    commonUseCases: [
      "Convert US scale readings to kilograms",
      "Translate fitness or medical weight targets",
      "Convert shipping weights to metric",
    ],
    sourceNotes: ["Conversion factor: 1 pound = 0.45359237 kilograms (international avoirdupois)."],
  }),
  buildLiveTool({
    id: "liters-to-gallons",
    slug: "liters-to-gallons",
    title: "Liters to Gallons Converter",
    category: "unit-converters",
    subcategory: "volume",
    shortDescription: "Convert liters to US gallons for fuel, liquid, and tank volumes.",
    metaTitle: "Liters to Gallons Converter - Free Volume Conversion",
    metaDescription:
      "Convert liters to US gallons instantly. Uses 1 US gallon = 3.785411784 liters with examples, formula, and reverse link.",
    keywords: ["liters to gallons", "litres to gallons", "l to gal"],
    relatedTools: ["gallons-to-liters", "kg-to-lbs", "lbs-to-kg"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "US gallons = liters ÷ 3.785411784",
    explanation: "Convert metric liquid volume from liters to US liquid gallons.",
    howToUse: [
      "Enter the volume in liters.",
      "View the US gallons result instantly.",
      "Use the reverse converter link for gallons to liters.",
    ],
    examples: [
      {
        title: "20 liters",
        input: "20",
        output: "5.283441",
        explanation: "20 ÷ 3.785411784 ≈ 5.28 US gallons.",
      },
    ],
    faqs: [
      faq("Does this use US or imperial gallons?", "This tool converts to US liquid gallons (3.785411784 liters)."),
      faq("Can I convert gallons back to liters?", "Yes. Use the Gallons to Liters converter."),
      faq("Can I enter decimal liters?", "Yes. Decimal liter values are supported."),
    ],
    commonUseCases: [
      "Convert fuel tank capacity for US vehicles",
      "Translate beverage or chemical volumes",
      "Compare metric and US liquid measurements",
    ],
    sourceNotes: ["Conversion factor: 1 US liquid gallon = 3.785411784 liters."],
  }),
  buildLiveTool({
    id: "gallons-to-liters",
    slug: "gallons-to-liters",
    title: "Gallons to Liters Converter",
    category: "unit-converters",
    subcategory: "volume",
    shortDescription: "Convert US gallons to liters for metric liquid volume.",
    metaTitle: "Gallons to Liters Converter - Free Volume Conversion",
    metaDescription:
      "Convert US gallons to liters instantly. Uses liters = gallons × 3.785411784 with examples, formula, and reverse link.",
    keywords: ["gallons to liters", "gallons to litres", "gal to l"],
    relatedTools: ["liters-to-gallons", "kg-to-lbs", "lbs-to-kg"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "liters = US gallons × 3.785411784",
    explanation: "Convert US liquid gallons to metric liters.",
    howToUse: [
      "Enter the volume in US gallons.",
      "View the liters result instantly.",
      "Use the reverse converter link for liters to gallons.",
    ],
    examples: [
      {
        title: "5 US gallons",
        input: "5",
        output: "18.927059",
        explanation: "5 × 3.785411784 ≈ 18.93 liters.",
      },
    ],
    faqs: [
      faq("Is this for US liquid gallons?", "Yes. It uses the US liquid gallon definition of 3.785411784 liters."),
      faq("How do I convert liters to gallons?", "Use the Liters to Gallons converter."),
      faq("Does this support fuel tank sizes?", "Yes. Enter gallon capacity to get liters."),
    ],
    commonUseCases: [
      "Convert US fuel economy references to metric",
      "Translate recipe or chemical volumes",
      "Compare container sizes across standards",
    ],
    sourceNotes: ["Conversion factor: 1 US liquid gallon = 3.785411784 liters."],
  }),
  buildLiveTool({
    id: "celsius-to-fahrenheit",
    slug: "celsius-to-fahrenheit",
    title: "Celsius to Fahrenheit Converter",
    category: "unit-converters",
    subcategory: "temperature",
    shortDescription: "Convert Celsius temperatures to Fahrenheit.",
    metaTitle: "Celsius to Fahrenheit Converter - Free Temperature Conversion",
    metaDescription:
      "Convert Celsius to Fahrenheit instantly. Uses °F = (°C × 9/5) + 32 with examples, formula, and reverse conversion link.",
    keywords: ["celsius to fahrenheit", "c to f", "centigrade to fahrenheit"],
    relatedTools: ["fahrenheit-to-celsius", "liters-to-gallons", "kg-to-lbs"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "°F = (°C × 9/5) + 32",
    explanation: "Convert metric Celsius temperatures to Fahrenheit using the standard linear formula.",
    howToUse: [
      "Enter the temperature in Celsius.",
      "View the Fahrenheit result instantly.",
      "Use the reverse converter link for Fahrenheit to Celsius.",
    ],
    examples: [
      {
        title: "25 °C",
        input: "25",
        output: "77",
        explanation: "(25 × 9/5) + 32 = 77 °F.",
      },
    ],
    faqs: [
      faq("Does this support negative Celsius values?", "Yes. Sub-zero Celsius temperatures convert correctly."),
      faq("Can I convert Fahrenheit back?", "Yes. Use the Fahrenheit to Celsius converter."),
      faq("Is 0 °C the same as 32 °F?", "Yes. Water freezes at 0 °C and 32 °F."),
    ],
    commonUseCases: [
      "Convert weather forecasts for US audiences",
      "Translate oven or cooking temperatures",
      "Convert lab or HVAC setpoints",
    ],
    sourceNotes: ["Formula: Fahrenheit = (Celsius × 9/5) + 32."],
  }),
  buildLiveTool({
    id: "fahrenheit-to-celsius",
    slug: "fahrenheit-to-celsius",
    title: "Fahrenheit to Celsius Converter",
    category: "unit-converters",
    subcategory: "temperature",
    shortDescription: "Convert Fahrenheit temperatures to Celsius.",
    metaTitle: "Fahrenheit to Celsius Converter - Free Temperature Conversion",
    metaDescription:
      "Convert Fahrenheit to Celsius instantly. Uses °C = (°F − 32) × 5/9 with examples, formula, and reverse conversion link.",
    keywords: ["fahrenheit to celsius", "f to c", "fahrenheit to centigrade"],
    relatedTools: ["celsius-to-fahrenheit", "liters-to-gallons", "kg-to-lbs"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "°C = (°F − 32) × 5/9",
    explanation: "Convert Fahrenheit temperatures to Celsius using the standard linear formula.",
    howToUse: [
      "Enter the temperature in Fahrenheit.",
      "View the Celsius result instantly.",
      "Use the reverse converter link for Celsius to Fahrenheit.",
    ],
    examples: [
      {
        title: "98.6 °F",
        input: "98.6",
        output: "37",
        explanation: "(98.6 − 32) × 5/9 = 37 °C.",
      },
    ],
    faqs: [
      faq("Can I convert body temperature?", "Yes. Enter Fahrenheit values such as 98.6 to get Celsius."),
      faq("How do I convert Celsius to Fahrenheit?", "Use the Celsius to Fahrenheit converter."),
      faq("Does this support decimals?", "Yes. Decimal Fahrenheit values are supported."),
    ],
    commonUseCases: [
      "Convert US weather reports to Celsius",
      "Translate oven settings on imported appliances",
      "Convert medical or fitness temperature readings",
    ],
    sourceNotes: ["Formula: Celsius = (Fahrenheit − 32) × 5/9."],
  }),
  buildLiveTool({
    id: "mb-to-gb",
    slug: "mb-to-gb",
    title: "MB to GB Converter",
    category: "unit-converters",
    subcategory: "digital-storage",
    shortDescription: "Convert megabytes to gigabytes using binary (1024-based) units.",
    metaTitle: "MB to GB Converter - Megabytes to Gigabytes Online",
    metaDescription:
      "Convert MB to GB instantly. Uses binary division by 1024 with examples, formula, and reverse conversion link.",
    keywords: ["mb to gb", "megabytes to gigabytes", "convert mb to gb"],
    relatedTools: ["gb-to-mb", "miles-to-km", "km-to-miles"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "gigabytes = megabytes ÷ 1024",
    explanation: "Convert digital storage from megabytes to gigabytes using binary (IEC) units.",
    howToUse: [
      "Enter the size in megabytes.",
      "View the gigabytes result instantly.",
      "Use the reverse converter link for GB to MB.",
    ],
    examples: [
      {
        title: "512 megabytes",
        input: "512",
        output: "0.5",
        explanation: "512 ÷ 1024 = 0.5 gigabytes.",
      },
    ],
    faqs: [
      faq("Does this use 1024 or 1000?", "This tool uses binary units where 1 GB = 1024 MB."),
      faq("Can I convert GB back to MB?", "Yes. Use the GB to MB converter."),
      faq("Is this for RAM and file sizes?", "Yes. Binary MB/GB is common for memory and many file size displays."),
    ],
    commonUseCases: [
      "Convert download sizes for storage planning",
      "Translate memory specs to gigabytes",
      "Estimate file batches for backup capacity",
    ],
    sourceNotes: ["Binary conversion: 1 gigabyte (GB) = 1024 megabytes (MB)."],
  }),
  buildLiveTool({
    id: "gb-to-mb",
    slug: "gb-to-mb",
    title: "GB to MB Converter",
    category: "unit-converters",
    subcategory: "digital-storage",
    shortDescription: "Convert gigabytes to megabytes using binary (1024-based) units.",
    metaTitle: "GB to MB Converter - Gigabytes to Megabytes Online",
    metaDescription:
      "Convert GB to MB instantly. Uses binary multiplication by 1024 with examples, formula, and reverse conversion link.",
    keywords: ["gb to mb", "gigabytes to megabytes", "convert gb to mb"],
    relatedTools: ["mb-to-gb", "miles-to-km", "km-to-miles"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "megabytes = gigabytes × 1024",
    explanation: "Convert digital storage from gigabytes to megabytes using binary (IEC) units.",
    howToUse: [
      "Enter the size in gigabytes.",
      "View the megabytes result instantly.",
      "Use the reverse converter link for MB to GB.",
    ],
    examples: [
      {
        title: "2 gigabytes",
        input: "2",
        output: "2,048",
        explanation: "2 × 1024 = 2,048 megabytes.",
      },
    ],
    faqs: [
      faq("Does this use binary gigabytes?", "Yes. 1 GB equals 1024 MB in this calculator."),
      faq("How do I convert MB to GB?", "Use the MB to GB converter."),
      faq("Can I enter decimal gigabytes?", "Yes. Decimal gigabyte values are supported."),
    ],
    commonUseCases: [
      "Convert storage quotas to megabytes",
      "Translate RAM or disk specs for comparison",
      "Estimate upload limits in MB",
    ],
    sourceNotes: ["Binary conversion: 1 gigabyte (GB) = 1024 megabytes (MB)."],
  }),
  buildLiveTool({
    id: "inches-to-cm",
    slug: "inches-to-cm",
    title: "Inches to CM Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert inches to centimeters instantly.",
    metaTitle: "Inches to CM Converter - Inches to Centimeters",
    metaDescription:
      "Convert inches to centimeters online. Free inches to cm converter using 1 inch = 2.54 cm with examples.",
    keywords: ["inches to cm", "inch to centimeter", "inches to centimeters converter", "in to cm"],
    relatedTools: ["cm-to-inches", "meters-to-feet", "feet-to-meters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "cm = inches × 2.54",
    explanation: "Convert length from US customary inches to metric centimeters using the standard 2.54 conversion factor.",
    howToUse: ["Enter inches.", "View centimeters instantly.", "Use the reverse converter for cm to inches."],
    examples: [
      { title: "12 inches (1 foot)", input: "12", output: "30.48", explanation: "12 × 2.54 = 30.48 cm.", prefillValue: "12" },
      { title: "6 inches", input: "6", output: "15.24", explanation: "6 × 2.54 = 15.24 cm.", prefillValue: "6" },
    ],
    faqs: [
      faq("How many cm in an inch?", "One inch equals exactly 2.54 centimeters by international definition."),
      faq("Can I convert fractional inches?", "Yes. Enter decimal values like 5.5 inches."),
      faq("Is this the same as in to cm?", "Yes. in, inch, and inches all convert using the same factor."),
    ],
    commonUseCases: ["Convert screen and print dimensions", "Translate US product specs to metric", "Convert height measurements"],
    sourceNotes: ["NIST: 1 inch = 2.54 cm exactly."],
  }),
  buildLiveTool({
    id: "cm-to-inches",
    slug: "cm-to-inches",
    title: "CM to Inches Converter",
    category: "unit-converters",
    subcategory: "length",
    shortDescription: "Convert centimeters to inches instantly.",
    metaTitle: "CM to Inches Converter - Centimeters to Inches",
    metaDescription:
      "Convert centimeters to inches online. Free cm to inches converter using 1 cm = 0.3937 inches with examples.",
    keywords: ["cm to inches", "centimeter to inch", "cm to in converter", "centimeters to inches"],
    relatedTools: ["inches-to-cm", "meters-to-feet", "feet-to-meters"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "inches = cm ÷ 2.54",
    explanation: "Convert length from metric centimeters to US customary inches.",
    howToUse: ["Enter centimeters.", "View inches instantly.", "Use the reverse converter for inches to cm."],
    examples: [
      { title: "30.48 cm (12 inches)", input: "30.48", output: "12", explanation: "30.48 ÷ 2.54 = 12 inches.", prefillValue: "30.48" },
      { title: "100 cm", input: "100", output: "39.370079", explanation: "100 ÷ 2.54 ≈ 39.37 inches.", prefillValue: "100" },
    ],
    faqs: [
      faq("How many inches in a centimeter?", "One centimeter equals approximately 0.3937 inches."),
      faq("Can I convert mm to inches here?", "Enter centimeters (mm ÷ 10) or use a dedicated mm converter."),
      faq("Is the conversion exact?", "Based on the exact 2.54 cm per inch definition."),
    ],
    commonUseCases: ["Convert metric product dimensions to inches", "Translate EU clothing sizes", "Convert design specs for US manufacturing"],
    sourceNotes: ["NIST: 1 inch = 2.54 cm exactly."],
  }),
];

export const expandedLiveTools: ToolDefinition[] = [
  ...baseConverterTools,
  ...expandedUnitPairTools,
  ...expandedUnitPairTools2,
];
