import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

export type UnitPairMeta = {
  id: string;
  slug: string;
  title: string;
  subcategory: string;
  shortDescription: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  formula: string;
  explanation: string;
  exampleTitle: string;
  exampleInput: string;
  exampleOutput: string;
  exampleExplanation: string;
  reverseId: string;
  relatedTools: string[];
  sourceNote: string;
  priority?: number;
};

export const buildUnitConverterTool = (meta: UnitPairMeta): ToolDefinition =>
  buildLiveTool({
    id: meta.id,
    slug: meta.slug,
    title: meta.title,
    category: "unit-converters",
    subcategory: meta.subcategory,
    shortDescription: meta.shortDescription,
    metaTitle: meta.metaTitle,
    metaDescription: meta.metaDescription,
    keywords: meta.keywords,
    relatedTools: [meta.reverseId, ...meta.relatedTools],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: meta.formula,
    explanation: meta.explanation,
    priority: meta.priority,
    howToUse: [
      `Enter the value in ${meta.title.split(" to ")[0]?.toLowerCase() ?? "source units"}.`,
      "View the converted result instantly.",
      "Use the reverse converter link for the opposite conversion.",
    ],
    examples: [
      {
        title: meta.exampleTitle,
        input: meta.exampleInput,
        output: meta.exampleOutput,
        explanation: meta.exampleExplanation,
        prefillValue: meta.exampleInput,
      },
    ],
    faqs: [
      faq("Can I convert back to the original unit?", `Yes. Use the reverse ${meta.title.includes("Converter") ? meta.title.replace(meta.slug.split("-to-")[0] ?? "", meta.reverseId.split("-to-")[0] ?? "") : "converter"}.`),
      faq("Does this support decimal values?", "Yes. Decimal inputs are supported."),
      faq("Is this conversion exact?", "This tool uses standard published conversion factors."),
    ],
    commonUseCases: [
      "Convert measurements for projects and listings",
      "Switch between metric and US customary units",
      "Quick reference for everyday unit math",
    ],
    sourceNotes: [meta.sourceNote],
  });

export const expandedUnitPairTools: ToolDefinition[] = [
  buildUnitConverterTool({
    id: "square-meters-to-square-feet",
    slug: "square-meters-to-square-feet",
    title: "Square Meters to Square Feet Converter",
    subcategory: "area",
    shortDescription: "Convert square meters to square feet for floor area and property size.",
    metaTitle: "Square Meters to Square Feet Converter - Free Area Conversion",
    metaDescription: "Convert square meters to square feet instantly. Uses 1 m² = 10.7639 ft² with formula and reverse link.",
    keywords: ["square meters to square feet", "sq m to sq ft", "m2 to ft2"],
    formula: "square feet = square meters × 10.7639104167",
    explanation: "Convert metric floor area from square meters to US customary square feet.",
    exampleTitle: "100 square meters",
    exampleInput: "100",
    exampleOutput: "1,076.391042",
    exampleExplanation: "100 × 10.7639104167 ≈ 1,076.39 square feet.",
    reverseId: "square-feet-to-square-meters",
    relatedTools: ["acres-to-square-feet", "square-feet-to-acres", "meters-to-feet"],
    sourceNote: "1 square meter = 10.7639104167 square feet.",
    priority: 12,
  }),
  buildUnitConverterTool({
    id: "square-feet-to-square-meters",
    slug: "square-feet-to-square-meters",
    title: "Square Feet to Square Meters Converter",
    subcategory: "area",
    shortDescription: "Convert square feet to square meters for metric area measurements.",
    metaTitle: "Square Feet to Square Meters Converter - Free Area Conversion",
    metaDescription: "Convert square feet to square meters instantly. Uses m² = ft² ÷ 10.7639 with formula and reverse link.",
    keywords: ["square feet to square meters", "sq ft to sq m", "ft2 to m2"],
    formula: "square meters = square feet ÷ 10.7639104167",
    explanation: "Convert US customary floor area from square feet to metric square meters.",
    exampleTitle: "1,000 square feet",
    exampleInput: "1000",
    exampleOutput: "92.90304",
    exampleExplanation: "1,000 ÷ 10.7639104167 ≈ 92.90 square meters.",
    reverseId: "square-meters-to-square-feet",
    relatedTools: ["acres-to-square-feet", "square-feet-to-acres", "feet-to-meters"],
    sourceNote: "1 square foot = 0.09290304 square meters.",
  }),
  buildUnitConverterTool({
    id: "mm-to-inches",
    slug: "mm-to-inches",
    title: "MM to Inches Converter",
    subcategory: "length",
    shortDescription: "Convert millimeters to inches for precision measurements.",
    metaTitle: "MM to Inches Converter - Millimeters to Inches",
    metaDescription: "Convert millimeters to inches online. Uses 1 inch = 25.4 mm with examples and reverse link.",
    keywords: ["mm to inches", "millimeters to inches", "mm to in"],
    formula: "inches = millimeters ÷ 25.4",
    explanation: "Convert metric millimeters to US customary inches.",
    exampleTitle: "25.4 millimeters",
    exampleInput: "25.4",
    exampleOutput: "1",
    exampleExplanation: "25.4 ÷ 25.4 = 1 inch.",
    reverseId: "inches-to-mm",
    relatedTools: ["cm-to-inches", "inches-to-cm", "meters-to-feet"],
    sourceNote: "NIST: 1 inch = 25.4 mm exactly.",
  }),
  buildUnitConverterTool({
    id: "inches-to-mm",
    slug: "inches-to-mm",
    title: "Inches to MM Converter",
    subcategory: "length",
    shortDescription: "Convert inches to millimeters for metric precision.",
    metaTitle: "Inches to MM Converter - Inches to Millimeters",
    metaDescription: "Convert inches to millimeters online. Uses mm = inches × 25.4 with examples and reverse link.",
    keywords: ["inches to mm", "inches to millimeters", "in to mm"],
    formula: "millimeters = inches × 25.4",
    explanation: "Convert US customary inches to metric millimeters.",
    exampleTitle: "1 inch",
    exampleInput: "1",
    exampleOutput: "25.4",
    exampleExplanation: "1 × 25.4 = 25.4 millimeters.",
    reverseId: "mm-to-inches",
    relatedTools: ["cm-to-inches", "inches-to-cm", "feet-to-meters"],
    sourceNote: "NIST: 1 inch = 25.4 mm exactly.",
  }),
  buildUnitConverterTool({
    id: "yards-to-meters",
    slug: "yards-to-meters",
    title: "Yards to Meters Converter",
    subcategory: "length",
    shortDescription: "Convert yards to meters for metric length measurements.",
    metaTitle: "Yards to Meters Converter - Free Length Conversion",
    metaDescription: "Convert yards to meters instantly. Uses 1 yard = 0.9144 m with examples and reverse link.",
    keywords: ["yards to meters", "yard to meter", "yd to m"],
    formula: "meters = yards ÷ 1.0936132983",
    explanation: "Convert US customary yards to metric meters.",
    exampleTitle: "100 yards",
    exampleInput: "100",
    exampleOutput: "91.44",
    exampleExplanation: "100 ÷ 1.0936132983 ≈ 91.44 meters.",
    reverseId: "meters-to-yards",
    relatedTools: ["feet-to-meters", "meters-to-feet", "miles-to-km"],
    sourceNote: "1 yard = 0.9144 meters (international yard).",
  }),
  buildUnitConverterTool({
    id: "meters-to-yards",
    slug: "meters-to-yards",
    title: "Meters to Yards Converter",
    subcategory: "length",
    shortDescription: "Convert meters to yards for US customary length.",
    metaTitle: "Meters to Yards Converter - Free Length Conversion",
    metaDescription: "Convert meters to yards instantly. Uses yards = meters × 1.0936132983 with examples and reverse link.",
    keywords: ["meters to yards", "meter to yard", "m to yd"],
    formula: "yards = meters × 1.0936132983",
    explanation: "Convert metric meters to US customary yards.",
    exampleTitle: "100 meters",
    exampleInput: "100",
    exampleOutput: "109.36133",
    exampleExplanation: "100 × 1.0936132983 ≈ 109.36 yards.",
    reverseId: "yards-to-meters",
    relatedTools: ["feet-to-meters", "meters-to-feet", "km-to-miles"],
    sourceNote: "1 meter = 1.0936132983 yards.",
  }),
  buildUnitConverterTool({
    id: "feet-to-inches",
    slug: "feet-to-inches",
    title: "Feet to Inches Converter",
    subcategory: "length",
    shortDescription: "Convert feet to inches for height and length measurements.",
    metaTitle: "Feet to Inches Converter - Free Length Conversion",
    metaDescription: "Convert feet to inches instantly. Uses 1 foot = 12 inches with examples and reverse link.",
    keywords: ["feet to inches", "ft to in", "foot to inch"],
    formula: "inches = feet × 12",
    explanation: "Convert feet to inches within the US customary system.",
    exampleTitle: "6 feet",
    exampleInput: "6",
    exampleOutput: "72",
    exampleExplanation: "6 × 12 = 72 inches.",
    reverseId: "inches-to-feet",
    relatedTools: ["inches-to-cm", "cm-to-inches", "meters-to-feet"],
    sourceNote: "1 foot = 12 inches exactly.",
  }),
  buildUnitConverterTool({
    id: "inches-to-feet",
    slug: "inches-to-feet",
    title: "Inches to Feet Converter",
    subcategory: "length",
    shortDescription: "Convert inches to feet for height and length measurements.",
    metaTitle: "Inches to Feet Converter - Free Length Conversion",
    metaDescription: "Convert inches to feet instantly. Uses feet = inches ÷ 12 with examples and reverse link.",
    keywords: ["inches to feet", "in to ft", "inch to foot"],
    formula: "feet = inches ÷ 12",
    explanation: "Convert inches to feet within the US customary system.",
    exampleTitle: "72 inches",
    exampleInput: "72",
    exampleOutput: "6",
    exampleExplanation: "72 ÷ 12 = 6 feet.",
    reverseId: "feet-to-inches",
    relatedTools: ["inches-to-cm", "cm-to-inches", "feet-to-meters"],
    sourceNote: "1 foot = 12 inches exactly.",
  }),
  buildUnitConverterTool({
    id: "ounces-to-grams",
    slug: "ounces-to-grams",
    title: "Ounces to Grams Converter",
    subcategory: "weight",
    shortDescription: "Convert ounces to grams for cooking and shipping weights.",
    metaTitle: "Ounces to Grams Converter - Free Weight Conversion",
    metaDescription: "Convert ounces to grams instantly. Uses 1 oz = 28.3495 g with examples and reverse link.",
    keywords: ["ounces to grams", "oz to g", "ounce to gram"],
    formula: "grams = ounces × 28.349523125",
    explanation: "Convert US customary ounces to metric grams.",
    exampleTitle: "8 ounces",
    exampleInput: "8",
    exampleOutput: "226.796185",
    exampleExplanation: "8 × 28.349523125 ≈ 226.80 grams.",
    reverseId: "grams-to-ounces",
    relatedTools: ["kg-to-lbs", "lbs-to-kg", "cups-to-grams"],
    sourceNote: "1 avoirdupois ounce = 28.349523125 grams.",
  }),
  buildUnitConverterTool({
    id: "grams-to-ounces",
    slug: "grams-to-ounces",
    title: "Grams to Ounces Converter",
    subcategory: "weight",
    shortDescription: "Convert grams to ounces for US customary weight.",
    metaTitle: "Grams to Ounces Converter - Free Weight Conversion",
    metaDescription: "Convert grams to ounces instantly. Uses oz = g ÷ 28.3495 with examples and reverse link.",
    keywords: ["grams to ounces", "g to oz", "gram to ounce"],
    formula: "ounces = grams ÷ 28.349523125",
    explanation: "Convert metric grams to US customary ounces.",
    exampleTitle: "100 grams",
    exampleInput: "100",
    exampleOutput: "3.527396",
    exampleExplanation: "100 ÷ 28.349523125 ≈ 3.53 ounces.",
    reverseId: "ounces-to-grams",
    relatedTools: ["kg-to-lbs", "lbs-to-kg", "cups-to-grams"],
    sourceNote: "1 gram = 0.0352739619 avoirdupois ounces.",
  }),
  buildUnitConverterTool({
    id: "cubic-feet-to-cubic-yards",
    slug: "cubic-feet-to-cubic-yards",
    title: "Cubic Feet to Cubic Yards Converter",
    subcategory: "volume",
    shortDescription: "Convert cubic feet to cubic yards for concrete and bulk materials.",
    metaTitle: "Cubic Feet to Cubic Yards Converter - Volume Conversion",
    metaDescription: "Convert cubic feet to cubic yards instantly. Uses 1 cu yd = 27 cu ft with examples and reverse link.",
    keywords: ["cubic feet to cubic yards", "cu ft to cu yd"],
    formula: "cubic yards = cubic feet ÷ 27",
    explanation: "Convert cubic feet to cubic yards for construction and landscaping volume.",
    exampleTitle: "27 cubic feet",
    exampleInput: "27",
    exampleOutput: "1",
    exampleExplanation: "27 ÷ 27 = 1 cubic yard.",
    reverseId: "cubic-yards-to-cubic-feet",
    relatedTools: ["liters-to-gallons", "gallons-to-liters", "concrete-calculator"],
    sourceNote: "1 cubic yard = 27 cubic feet.",
  }),
  buildUnitConverterTool({
    id: "cubic-yards-to-cubic-feet",
    slug: "cubic-yards-to-cubic-feet",
    title: "Cubic Yards to Cubic Feet Converter",
    subcategory: "volume",
    shortDescription: "Convert cubic yards to cubic feet for material volume estimates.",
    metaTitle: "Cubic Yards to Cubic Feet Converter - Volume Conversion",
    metaDescription: "Convert cubic yards to cubic feet instantly. Uses cu ft = cu yd × 27 with examples and reverse link.",
    keywords: ["cubic yards to cubic feet", "cu yd to cu ft"],
    formula: "cubic feet = cubic yards × 27",
    explanation: "Convert cubic yards to cubic feet for construction and landscaping volume.",
    exampleTitle: "2 cubic yards",
    exampleInput: "2",
    exampleOutput: "54",
    exampleExplanation: "2 × 27 = 54 cubic feet.",
    reverseId: "cubic-feet-to-cubic-yards",
    relatedTools: ["liters-to-gallons", "gravel-calculator", "mulch-calculator"],
    sourceNote: "1 cubic yard = 27 cubic feet.",
  }),
  buildUnitConverterTool({
    id: "celsius-to-kelvin",
    slug: "celsius-to-kelvin",
    title: "Celsius to Kelvin Converter",
    subcategory: "temperature",
    shortDescription: "Convert Celsius temperatures to Kelvin.",
    metaTitle: "Celsius to Kelvin Converter - Free Temperature Conversion",
    metaDescription: "Convert Celsius to Kelvin instantly. Uses K = °C + 273.15 with examples and reverse link.",
    keywords: ["celsius to kelvin", "c to k", "centigrade to kelvin"],
    formula: "K = °C + 273.15",
    explanation: "Convert Celsius to Kelvin using the standard offset.",
    exampleTitle: "25 °C",
    exampleInput: "25",
    exampleOutput: "298.15",
    exampleExplanation: "25 + 273.15 = 298.15 K.",
    reverseId: "kelvin-to-celsius",
    relatedTools: ["celsius-to-fahrenheit", "fahrenheit-to-celsius", "fahrenheit-to-kelvin"],
    sourceNote: "Kelvin = Celsius + 273.15.",
  }),
  buildUnitConverterTool({
    id: "kelvin-to-celsius",
    slug: "kelvin-to-celsius",
    title: "Kelvin to Celsius Converter",
    subcategory: "temperature",
    shortDescription: "Convert Kelvin temperatures to Celsius.",
    metaTitle: "Kelvin to Celsius Converter - Free Temperature Conversion",
    metaDescription: "Convert Kelvin to Celsius instantly. Uses °C = K − 273.15 with examples and reverse link.",
    keywords: ["kelvin to celsius", "k to c"],
    formula: "°C = K − 273.15",
    explanation: "Convert Kelvin to Celsius using the standard offset.",
    exampleTitle: "298.15 K",
    exampleInput: "298.15",
    exampleOutput: "25",
    exampleExplanation: "298.15 − 273.15 = 25 °C.",
    reverseId: "celsius-to-kelvin",
    relatedTools: ["celsius-to-fahrenheit", "fahrenheit-to-celsius", "kelvin-to-fahrenheit"],
    sourceNote: "Celsius = Kelvin − 273.15.",
  }),
  buildUnitConverterTool({
    id: "fahrenheit-to-kelvin",
    slug: "fahrenheit-to-kelvin",
    title: "Fahrenheit to Kelvin Converter",
    subcategory: "temperature",
    shortDescription: "Convert Fahrenheit temperatures to Kelvin.",
    metaTitle: "Fahrenheit to Kelvin Converter - Free Temperature Conversion",
    metaDescription: "Convert Fahrenheit to Kelvin instantly. Uses K = (°F − 32) × 5/9 + 273.15 with examples.",
    keywords: ["fahrenheit to kelvin", "f to k"],
    formula: "K = (°F − 32) × 5/9 + 273.15",
    explanation: "Convert Fahrenheit to Kelvin using the standard formula.",
    exampleTitle: "77 °F",
    exampleInput: "77",
    exampleOutput: "298.15",
    exampleExplanation: "(77 − 32) × 5/9 + 273.15 = 298.15 K.",
    reverseId: "kelvin-to-fahrenheit",
    relatedTools: ["fahrenheit-to-celsius", "celsius-to-kelvin", "celsius-to-fahrenheit"],
    sourceNote: "Kelvin = (Fahrenheit − 32) × 5/9 + 273.15.",
  }),
  buildUnitConverterTool({
    id: "kelvin-to-fahrenheit",
    slug: "kelvin-to-fahrenheit",
    title: "Kelvin to Fahrenheit Converter",
    subcategory: "temperature",
    shortDescription: "Convert Kelvin temperatures to Fahrenheit.",
    metaTitle: "Kelvin to Fahrenheit Converter - Free Temperature Conversion",
    metaDescription: "Convert Kelvin to Fahrenheit instantly. Uses °F = (K − 273.15) × 9/5 + 32 with examples.",
    keywords: ["kelvin to fahrenheit", "k to f"],
    formula: "°F = (K − 273.15) × 9/5 + 32",
    explanation: "Convert Kelvin to Fahrenheit using the standard formula.",
    exampleTitle: "298.15 K",
    exampleInput: "298.15",
    exampleOutput: "77",
    exampleExplanation: "(298.15 − 273.15) × 9/5 + 32 = 77 °F.",
    reverseId: "fahrenheit-to-kelvin",
    relatedTools: ["fahrenheit-to-celsius", "celsius-to-kelvin", "celsius-to-fahrenheit"],
    sourceNote: "Fahrenheit = (Kelvin − 273.15) × 9/5 + 32.",
  }),
  buildUnitConverterTool({
    id: "kb-to-mb",
    slug: "kb-to-mb",
    title: "KB to MB Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert kilobytes to megabytes using binary (1024-based) units.",
    metaTitle: "KB to MB Converter - Kilobytes to Megabytes Online",
    metaDescription: "Convert KB to MB instantly. Uses binary division by 1024 with examples and reverse link.",
    keywords: ["kb to mb", "kilobytes to megabytes"],
    formula: "megabytes = kilobytes ÷ 1024",
    explanation: "Convert digital storage from kilobytes to megabytes using binary units.",
    exampleTitle: "1024 kilobytes",
    exampleInput: "1024",
    exampleOutput: "1",
    exampleExplanation: "1024 ÷ 1024 = 1 megabyte.",
    reverseId: "mb-to-kb",
    relatedTools: ["mb-to-gb", "gb-to-mb", "gb-to-tb"],
    sourceNote: "Binary: 1 megabyte = 1024 kilobytes.",
  }),
  buildUnitConverterTool({
    id: "mb-to-kb",
    slug: "mb-to-kb",
    title: "MB to KB Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert megabytes to kilobytes using binary (1024-based) units.",
    metaTitle: "MB to KB Converter - Megabytes to Kilobytes Online",
    metaDescription: "Convert MB to KB instantly. Uses binary multiplication by 1024 with examples and reverse link.",
    keywords: ["mb to kb", "megabytes to kilobytes"],
    formula: "kilobytes = megabytes × 1024",
    explanation: "Convert digital storage from megabytes to kilobytes using binary units.",
    exampleTitle: "1 megabyte",
    exampleInput: "1",
    exampleOutput: "1,024",
    exampleExplanation: "1 × 1024 = 1,024 kilobytes.",
    reverseId: "kb-to-mb",
    relatedTools: ["mb-to-gb", "gb-to-mb", "gb-to-tb"],
    sourceNote: "Binary: 1 megabyte = 1024 kilobytes.",
  }),
  buildUnitConverterTool({
    id: "gb-to-tb",
    slug: "gb-to-tb",
    title: "GB to TB Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert gigabytes to terabytes using binary (1024-based) units.",
    metaTitle: "GB to TB Converter - Gigabytes to Terabytes Online",
    metaDescription: "Convert GB to TB instantly. Uses binary division by 1024 with examples and reverse link.",
    keywords: ["gb to tb", "gigabytes to terabytes"],
    formula: "terabytes = gigabytes ÷ 1024",
    explanation: "Convert digital storage from gigabytes to terabytes using binary units.",
    exampleTitle: "1024 gigabytes",
    exampleInput: "1024",
    exampleOutput: "1",
    exampleExplanation: "1024 ÷ 1024 = 1 terabyte.",
    reverseId: "tb-to-gb",
    relatedTools: ["mb-to-gb", "gb-to-mb", "kb-to-mb"],
    sourceNote: "Binary: 1 terabyte = 1024 gigabytes.",
  }),
  buildUnitConverterTool({
    id: "tb-to-gb",
    slug: "tb-to-gb",
    title: "TB to GB Converter",
    subcategory: "digital-storage",
    shortDescription: "Convert terabytes to gigabytes using binary (1024-based) units.",
    metaTitle: "TB to GB Converter - Terabytes to Gigabytes Online",
    metaDescription: "Convert TB to GB instantly. Uses binary multiplication by 1024 with examples and reverse link.",
    keywords: ["tb to gb", "terabytes to gigabytes"],
    formula: "gigabytes = terabytes × 1024",
    explanation: "Convert digital storage from terabytes to gigabytes using binary units.",
    exampleTitle: "1 terabyte",
    exampleInput: "1",
    exampleOutput: "1,024",
    exampleExplanation: "1 × 1024 = 1,024 gigabytes.",
    reverseId: "gb-to-tb",
    relatedTools: ["mb-to-gb", "gb-to-mb", "kb-to-mb"],
    sourceNote: "Binary: 1 terabyte = 1024 gigabytes.",
  }),
];
