import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

export const constructionMaterialConverterTools: ToolDefinition[] = [
  buildLiveTool({
    id: "gravel-cubic-yards-to-tons",
    slug: "gravel-cubic-yards-to-tons",
    title: "Gravel Cubic Yards to Tons Converter",
    category: "construction-calculators",
    subcategory: "landscaping",
    pathOverride: "/construction-calculators/landscaping/gravel-cubic-yards-to-tons/",
    shortDescription: "Convert gravel volume in cubic yards to approximate weight in tons.",
    metaTitle: "Gravel Cubic Yards to Tons Converter - Material Weight Estimate",
    metaDescription:
      "Convert gravel cubic yards to tons using ~1.4 tons per cubic yard. Free landscaping material estimate with assumptions noted.",
    keywords: ["gravel cubic yards to tons", "gravel yards to tons", "cu yd gravel to tons"],
    relatedTools: ["gravel-tons-to-cubic-yards", "gravel-calculator", "cubic-yards-to-cubic-feet"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "tons ≈ cubic yards × 1.4",
    explanation:
      "Estimate gravel weight in tons from cubic yard volume using a typical crushed stone density factor.",
    howToUse: [
      "Enter the gravel volume in cubic yards.",
      "View the approximate tonnage result.",
      "Use the gravel calculator for area-based volume estimates.",
    ],
    examples: [
      {
        title: "3.7 cubic yards",
        input: "3.7",
        output: "5.18",
        explanation: "3.7 × 1.4 ≈ 5.18 tons using the standard gravel factor.",
      },
    ],
    faqs: [
      faq("Is this exact weight?", "No. Actual tonnage varies by stone type, moisture, and compaction."),
      faq("What density is used?", "This tool uses approximately 1.4 tons per cubic yard for crushed gravel."),
      faq("Can I convert tons back to yards?", "Yes. Use the Gravel Tons to Cubic Yards converter."),
    ],
    commonUseCases: [
      "Compare supplier quotes in yards vs tons",
      "Estimate driveway gravel delivery weight",
      "Plan truck loads for landscaping projects",
    ],
    assumptions: [
      "Uses ~1.4 tons per cubic yard for crushed gravel (matches gravel calculator default).",
      "Moisture content and stone type can change actual weight.",
    ],
    sourceNotes: ["Typical crushed stone: ~1.4 tons per cubic yard."],
  }),
  buildLiveTool({
    id: "gravel-tons-to-cubic-yards",
    slug: "gravel-tons-to-cubic-yards",
    title: "Gravel Tons to Cubic Yards Converter",
    category: "construction-calculators",
    subcategory: "landscaping",
    pathOverride: "/construction-calculators/landscaping/gravel-tons-to-cubic-yards/",
    shortDescription: "Convert gravel weight in tons to approximate volume in cubic yards.",
    metaTitle: "Gravel Tons to Cubic Yards Converter - Volume Estimate",
    metaDescription:
      "Convert gravel tons to cubic yards using ~1.4 tons per cubic yard. Free reverse material conversion with assumptions.",
    keywords: ["gravel tons to cubic yards", "tons gravel to cu yd"],
    relatedTools: ["gravel-cubic-yards-to-tons", "gravel-calculator", "cubic-feet-to-cubic-yards"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "cubic yards ≈ tons ÷ 1.4",
    explanation: "Estimate gravel volume in cubic yards from tonnage using a typical crushed stone density factor.",
    howToUse: ["Enter gravel weight in tons.", "View approximate cubic yards.", "Cross-check with the gravel calculator."],
    examples: [
      { title: "5.18 tons", input: "5.18", output: "3.7", explanation: "5.18 ÷ 1.4 ≈ 3.7 cubic yards." },
    ],
    faqs: [
      faq("Does stone type matter?", "Yes. Dense river rock and lighter lava rock differ from crushed gravel averages."),
      faq("What factor is used?", "Approximately 1.4 tons per cubic yard."),
    ],
    commonUseCases: ["Convert supplier ton quotes to cubic yards", "Verify delivery ticket volumes"],
    assumptions: ["Uses ~1.4 tons per cubic yard for crushed gravel."],
    sourceNotes: ["Typical crushed stone: ~1.4 tons per cubic yard."],
  }),
  buildLiveTool({
    id: "mulch-cubic-yards-to-tons",
    slug: "mulch-cubic-yards-to-tons",
    title: "Mulch Cubic Yards to Tons Converter",
    category: "construction-calculators",
    subcategory: "landscaping",
    pathOverride: "/construction-calculators/landscaping/mulch-cubic-yards-to-tons/",
    shortDescription: "Convert mulch volume in cubic yards to approximate weight in tons.",
    metaTitle: "Mulch Cubic Yards to Tons Converter - Landscaping Estimate",
    metaDescription:
      "Convert mulch cubic yards to tons using ~0.55 tons per cubic yard. Free estimate for bark and wood mulch orders.",
    keywords: ["mulch cubic yards to tons", "mulch yards to tons"],
    relatedTools: ["mulch-tons-to-cubic-yards", "mulch-calculator", "cubic-yards-to-cubic-feet"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "tons ≈ cubic yards × 0.55",
    explanation: "Estimate mulch weight from cubic yard volume using a mid-range bark mulch density.",
    howToUse: ["Enter mulch volume in cubic yards.", "View approximate tons.", "Use the mulch calculator for bed coverage."],
    examples: [
      { title: "5 cubic yards", input: "5", output: "2.75", explanation: "5 × 0.55 = 2.75 tons." },
    ],
    faqs: [
      faq("Why is mulch lighter than gravel?", "Mulch is less dense than crushed stone; moisture also affects weight."),
      faq("What density is assumed?", "About 0.55 tons per cubic yard (roughly 0.5–0.6 depending on mulch type)."),
    ],
    commonUseCases: ["Estimate mulch delivery weight", "Compare bulk vs bagged mulch orders"],
    assumptions: ["Uses ~0.55 tons per cubic yard for bark/wood mulch."],
    sourceNotes: ["Mulch density varies from ~0.4 to ~0.6 tons per cubic yard depending on type and moisture."],
  }),
  buildLiveTool({
    id: "mulch-tons-to-cubic-yards",
    slug: "mulch-tons-to-cubic-yards",
    title: "Mulch Tons to Cubic Yards Converter",
    category: "construction-calculators",
    subcategory: "landscaping",
    pathOverride: "/construction-calculators/landscaping/mulch-tons-to-cubic-yards/",
    shortDescription: "Convert mulch weight in tons to approximate volume in cubic yards.",
    metaTitle: "Mulch Tons to Cubic Yards Converter - Volume Estimate",
    metaDescription:
      "Convert mulch tons to cubic yards using ~0.55 tons per cubic yard. Free reverse landscaping material conversion.",
    keywords: ["mulch tons to cubic yards"],
    relatedTools: ["mulch-cubic-yards-to-tons", "mulch-calculator"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "cubic yards ≈ tons ÷ 0.55",
    explanation: "Estimate mulch volume from tonnage using a typical bark mulch density factor.",
    howToUse: ["Enter mulch weight in tons.", "View approximate cubic yards."],
    examples: [
      { title: "2.75 tons", input: "2.75", output: "5", explanation: "2.75 ÷ 0.55 = 5 cubic yards." },
    ],
    faqs: [faq("Is wet mulch heavier?", "Yes. Moisture can increase weight without increasing usable volume much.")],
    commonUseCases: ["Convert ton-based quotes to cubic yard coverage"],
    assumptions: ["Uses ~0.55 tons per cubic yard."],
    sourceNotes: ["Mulch density varies by type and moisture content."],
  }),
  buildLiveTool({
    id: "concrete-cubic-yards-to-tons",
    slug: "concrete-cubic-yards-to-tons",
    title: "Concrete Cubic Yards to Tons Converter",
    category: "construction-calculators",
    subcategory: "concrete-cement",
    pathOverride: "/construction-calculators/concrete-cement/concrete-cubic-yards-to-tons/",
    shortDescription: "Convert concrete volume in cubic yards to approximate weight in tons.",
    metaTitle: "Concrete Cubic Yards to Tons Converter - Slab Weight Estimate",
    metaDescription:
      "Convert concrete cubic yards to tons using ~2.0 tons per cubic yard. Free estimate for ready-mix orders and hauling.",
    keywords: ["concrete cubic yards to tons", "concrete yards to tons"],
    relatedTools: ["concrete-tons-to-cubic-yards", "concrete-calculator", "cement-calculator"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "tons ≈ cubic yards × 2.0",
    explanation: "Estimate concrete weight from cubic yard volume using a standard ready-mix density approximation.",
    howToUse: ["Enter concrete volume in cubic yards.", "View approximate tons.", "Use the concrete calculator for slab volume."],
    examples: [
      { title: "2 cubic yards", input: "2", output: "4", explanation: "2 × 2.0 = 4 tons." },
    ],
    faqs: [
      faq("Is this for wet concrete?", "Yes. It approximates typical ready-mix weight per cubic yard."),
      faq("What density is used?", "About 2.0 tons (4,000 lb) per cubic yard for normal-weight concrete."),
    ],
    commonUseCases: ["Estimate truck load weight for slabs", "Compare ready-mix quotes in yards vs tons"],
    assumptions: ["Uses ~2.0 tons per cubic yard for normal-weight concrete."],
    sourceNotes: ["Normal-weight concrete is approximately 4,000 lb (2 tons) per cubic yard."],
  }),
  buildLiveTool({
    id: "concrete-tons-to-cubic-yards",
    slug: "concrete-tons-to-cubic-yards",
    title: "Concrete Tons to Cubic Yards Converter",
    category: "construction-calculators",
    subcategory: "concrete-cement",
    pathOverride: "/construction-calculators/concrete-cement/concrete-tons-to-cubic-yards/",
    shortDescription: "Convert concrete weight in tons to approximate volume in cubic yards.",
    metaTitle: "Concrete Tons to Cubic Yards Converter - Volume Estimate",
    metaDescription:
      "Convert concrete tons to cubic yards using ~2.0 tons per cubic yard. Free reverse ready-mix volume estimate.",
    keywords: ["concrete tons to cubic yards"],
    relatedTools: ["concrete-cubic-yards-to-tons", "concrete-calculator"],
    componentKey: "GenericUnitConverterTool",
    schemaType: "Calculator",
    formula: "cubic yards ≈ tons ÷ 2.0",
    explanation: "Estimate concrete volume from tonnage using a standard ready-mix density approximation.",
    howToUse: ["Enter concrete weight in tons.", "View approximate cubic yards."],
    examples: [
      { title: "4 tons", input: "4", output: "2", explanation: "4 ÷ 2.0 = 2 cubic yards." },
    ],
    faqs: [faq("Does reinforcement change volume?", "Rebar and fiber add minimal volume; this estimates plain ready-mix volume.")],
    commonUseCases: ["Convert weight-based hauling limits to pour volume"],
    assumptions: ["Uses ~2.0 tons per cubic yard."],
    sourceNotes: ["Normal-weight concrete ≈ 4,000 lb per cubic yard."],
  }),
];
