import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

export const expandedLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "yaml-to-json",
    slug: "yaml-to-json",
    title: "YAML to JSON Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/yaml-to-json/",
    shortDescription: "Convert YAML configuration and data files into JSON for APIs and apps.",
    metaTitle: "YAML to JSON Converter - Convert YAML to JSON Online",
    metaDescription:
      "Convert YAML to JSON online. Paste YAML configs or data files and copy formatted JSON output instantly.",
    keywords: ["yaml to json", "yaml converter", "convert yaml to json"],
    relatedTools: ["json-to-yaml", "json-formatter", "json-to-csv"],
    componentKey: "GenericDataConverterTool",
    explanation: "Paste YAML and convert it into formatted JSON for APIs, configs, and testing.",
    howToUse: [
      "Paste YAML text into the input area.",
      "Review the generated JSON output.",
      "Copy or reuse the JSON in your application.",
    ],
    examples: [
      {
        title: "Simple config",
        input: "name: Ada\nrole: Engineer\nactive: true",
        output: '{\n  "name": "Ada",\n  "role": "Engineer",\n  "active": true\n}',
        explanation: "YAML keys become JSON object properties.",
      },
    ],
    faqs: [
      faq("Does this support nested YAML?", "Yes. Nested YAML maps convert to nested JSON objects."),
      faq("Can I convert JSON back to YAML?", "Yes. Use the JSON to YAML converter for the reverse workflow."),
      faq("Is my data uploaded?", "No. Conversion runs locally in your browser."),
    ],
    commonUseCases: ["Convert Kubernetes or CI YAML snippets", "Prepare config files for JSON APIs", "Debug YAML-based configs"],
  }),
  buildLiveTool({
    id: "json-to-yaml",
    slug: "json-to-yaml",
    title: "JSON to YAML Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/json-to-yaml/",
    shortDescription: "Convert JSON objects into readable YAML configuration files.",
    metaTitle: "JSON to YAML Converter - Convert JSON to YAML Online",
    metaDescription:
      "Convert JSON to YAML online. Paste JSON and generate clean YAML for configs, DevOps files, and documentation.",
    keywords: ["json to yaml", "json yaml converter"],
    relatedTools: ["yaml-to-json", "json-formatter", "csv-to-json"],
    componentKey: "GenericDataConverterTool",
    explanation: "Transform JSON into human-readable YAML for configs and infrastructure files.",
    howToUse: ["Paste valid JSON.", "Review the YAML output.", "Copy the YAML for your config files."],
    examples: [
      {
        title: "Object conversion",
        input: '{"service":"api","port":8080}',
        output: "service: api\nport: 8080",
        explanation: "JSON properties become YAML key-value pairs.",
      },
    ],
    faqs: [
      faq("What JSON formats are supported?", "Objects and arrays parsed by standard JSON syntax are supported."),
      faq("Will key order be preserved?", "YAML output follows the parser ordering from your JSON input."),
      faq("Can I convert YAML back?", "Yes. Use the YAML to JSON converter."),
    ],
    commonUseCases: ["Generate sample YAML configs", "Convert API JSON fixtures to YAML", "Prepare deployment config drafts"],
  }),
  buildLiveTool({
    id: "xml-to-json",
    slug: "xml-to-json",
    title: "XML to JSON Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/xml-to-json/",
    shortDescription: "Transform XML documents and API payloads into JSON objects.",
    metaTitle: "XML to JSON Converter - Convert XML to JSON Online",
    metaDescription:
      "Convert XML to JSON online. Parse XML payloads into JSON for APIs, tests, and data migration workflows.",
    keywords: ["xml to json", "xml converter"],
    relatedTools: ["json-formatter", "yaml-to-json", "csv-to-json"],
    componentKey: "GenericDataConverterTool",
    explanation: "Parse XML and output JSON using element names as object keys.",
    howToUse: ["Paste XML into the input area.", "Review the JSON output.", "Copy the JSON result."],
    examples: [
      {
        title: "Simple XML node",
        input: "<user><name>Ada</name><role>Engineer</role></user>",
        output: '{\n  "user": {\n    "name": "Ada",\n    "role": "Engineer"\n  }\n}',
        explanation: "XML elements map to JSON object keys.",
      },
    ],
    faqs: [
      faq("Are attributes supported?", "This first version focuses on element text and nested elements."),
      faq("What about repeated tags?", "Repeated sibling tags are grouped into JSON arrays when needed."),
      faq("Does this validate XML?", "Invalid XML returns a clear parse error."),
    ],
    commonUseCases: ["Convert legacy XML API responses", "Generate JSON test fixtures", "Inspect XML payload structure"],
  }),
  buildLiveTool({
    id: "json-to-xml",
    slug: "json-to-xml",
    title: "JSON to XML Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/json-to-xml/",
    shortDescription: "Convert JSON objects into XML documents for legacy APIs and integrations.",
    metaTitle: "JSON to XML Converter - Convert JSON to XML Online",
    metaDescription:
      "Convert JSON to XML online. Paste JSON and generate XML with nested elements for APIs, configs, and data migration.",
    keywords: ["json to xml", "json xml converter", "convert json to xml"],
    relatedTools: ["xml-to-json", "json-formatter", "json-to-yaml"],
    componentKey: "GenericDataConverterTool",
    explanation: "Transform JSON into XML using element names as tags with proper text escaping.",
    howToUse: ["Paste valid JSON.", "Review the XML output.", "Copy or download the XML result."],
    examples: [
      {
        title: "Nested object",
        input: '{"user":{"name":"Ada","role":"Engineer"}}',
        output: '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <user>\n    <name>Ada</name>\n    <role>Engineer</role>\n  </user>\n</root>',
        explanation: "JSON keys become XML element names.",
      },
    ],
    faqs: [
      faq("Does this support JSON arrays?", "Yes. Array items become repeated XML elements."),
      faq("Can I convert XML back to JSON?", "Yes. Use the XML to JSON converter."),
      faq("Is my data uploaded?", "No. Conversion runs locally in your browser."),
    ],
    commonUseCases: ["Generate XML payloads from JSON APIs", "Prepare legacy integration files", "Convert config exports"],
  }),
  buildLiveTool({
    id: "csv-to-yaml",
    slug: "csv-to-yaml",
    title: "CSV to YAML Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/csv-to-yaml/",
    shortDescription: "Convert CSV spreadsheets into YAML lists for configs and DevOps files.",
    metaTitle: "CSV to YAML Converter - Convert CSV to YAML Online",
    metaDescription:
      "Convert CSV to YAML online. Paste CSV with headers and generate YAML arrays for configs, CI files, and documentation.",
    keywords: ["csv to yaml", "csv yaml converter", "convert csv to yaml"],
    relatedTools: ["csv-to-json", "json-to-yaml", "yaml-to-json"],
    componentKey: "GenericDataConverterTool",
    explanation: "Parse CSV rows into objects and output readable YAML for configs and data files.",
    howToUse: ["Paste CSV with a header row.", "Review the YAML output.", "Copy or download the YAML result."],
    examples: [
      {
        title: "Two-row CSV",
        input: "id,name\n1,Ada\n2,Grace",
        output: "- id: \"1\"\n  name: Ada\n- id: \"2\"\n  name: Grace",
        explanation: "Each CSV row becomes a YAML list item with key-value pairs.",
      },
    ],
    faqs: [
      faq("Does this require a header row?", "Yes. The first CSV row is used as YAML keys."),
      faq("Can I convert YAML back to CSV?", "Convert YAML to JSON first, then use JSON to CSV."),
      faq("Are numbers preserved?", "Values are kept as strings from CSV unless you use CSV to JSON with type inference first."),
    ],
    commonUseCases: ["Convert spreadsheet exports to YAML configs", "Prepare CI fixture files", "Migrate tabular data to YAML"],
  }),
  buildLiveTool({
    id: "json-to-toml",
    slug: "json-to-toml",
    title: "JSON to TOML Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/json-to-toml/",
    shortDescription: "Convert JSON objects into TOML configuration files for Rust, Python, and DevOps tools.",
    metaTitle: "JSON to TOML Converter - Convert JSON to TOML Online",
    metaDescription:
      "Convert JSON to TOML online. Paste JSON and generate TOML config files for pyproject, Cargo, and more.",
    keywords: ["json to toml", "json toml converter"],
    relatedTools: ["toml-to-json", "json-to-yaml", "yaml-to-json"],
    componentKey: "GenericDataConverterTool",
    explanation: "Transform JSON into TOML for configs that require .toml format.",
    howToUse: ["Paste valid JSON.", "Review the TOML output.", "Copy or download the TOML result."],
    examples: [
      {
        title: "Simple config",
        input: '{"title":"My App","version":"1.0.0"}',
        output: 'title = "My App"\nversion = "1.0.0"',
        explanation: "JSON keys become TOML key-value pairs.",
      },
    ],
    faqs: [
      faq("Can I convert TOML back to JSON?", "Yes. Use the TOML to JSON converter."),
      faq("Is my data uploaded?", "No. Conversion runs locally in your browser."),
    ],
    commonUseCases: ["Generate pyproject.toml snippets", "Convert API JSON fixtures to TOML", "Prepare Rust/Cargo config drafts"],
  }),
  buildLiveTool({
    id: "toml-to-json",
    slug: "toml-to-json",
    title: "TOML to JSON Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/toml-to-json/",
    shortDescription: "Convert TOML configuration files into JSON for APIs and apps.",
    metaTitle: "TOML to JSON Converter - Convert TOML to JSON Online",
    metaDescription:
      "Convert TOML to JSON online. Paste TOML configs and get formatted JSON output instantly.",
    keywords: ["toml to json", "toml json converter"],
    relatedTools: ["json-to-toml", "yaml-to-json", "json-formatter"],
    componentKey: "GenericDataConverterTool",
    explanation: "Parse TOML configs and output formatted JSON.",
    howToUse: ["Paste TOML text.", "Review JSON output.", "Copy or download the result."],
    examples: [
      {
        title: "Simple TOML",
        input: 'name = "Ada"\nactive = true',
        output: '{\n  "name": "Ada",\n  "active": true\n}',
        explanation: "TOML tables and keys map to JSON objects.",
      },
    ],
    faqs: [
      faq("Does this support nested TOML tables?", "Yes. Nested tables convert to nested JSON objects."),
      faq("Can I convert JSON back to TOML?", "Yes. Use the JSON to TOML converter."),
    ],
    commonUseCases: ["Inspect TOML configs as JSON", "Convert Cargo/pyproject snippets for APIs"],
  }),
  buildLiveTool({
    id: "number-base-converter",
    slug: "number-base-converter",
    title: "Number Base Converter",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/number-base-converter/",
    shortDescription: "Convert numbers between binary, octal, decimal, and hexadecimal bases.",
    metaTitle: "Number Base Converter - Binary, Hex, Decimal Online",
    metaDescription:
      "Convert numbers between binary, octal, decimal, and hex online. Free developer base converter with swap and copy.",
    keywords: ["binary to hex", "hex to decimal", "number base converter", "binary converter"],
    relatedTools: ["base64-encode", "base64-decode", "hash-generator"],
    componentKey: "NumberBaseConverterTool",
    explanation: "Convert integers between base 2, 8, 10, and 16 with optional 0x/0b prefixes on output.",
    howToUse: ["Enter a number.", "Choose from and to bases.", "Copy the converted result."],
    examples: [
      { title: "255 decimal to hex", input: "255", output: "0xFF", explanation: "255 in base 10 equals FF in hexadecimal." },
    ],
    faqs: [
      faq("Can I use 0x or 0b prefixes?", "Yes. Prefixes are recognized on input and added on output when helpful."),
      faq("Does this support negative numbers?", "This version focuses on non-negative integer conversion."),
    ],
    commonUseCases: ["Debug hex memory addresses", "Convert binary flags to decimal", "Translate color hex values"],
  }),
  buildLiveTool({
    id: "tsv-to-csv",
    slug: "tsv-to-csv",
    title: "TSV to CSV Converter",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/tsv-to-csv/",
    shortDescription: "Convert tab-separated values into comma-separated CSV for spreadsheets.",
    metaTitle: "TSV to CSV Converter - Convert TSV to CSV Online",
    metaDescription:
      "Convert TSV to CSV online. Transform tab-separated exports into comma-separated CSV for Excel and data tools.",
    keywords: ["tsv to csv", "tab separated to csv"],
    relatedTools: ["csv-to-json", "json-to-csv", "nested-json-to-csv"],
    componentKey: "GenericDataConverterTool",
    explanation: "Convert tab-delimited rows into CSV with proper quoting when needed.",
    howToUse: ["Paste TSV data with tab-separated columns.", "Review CSV output.", "Copy or download the CSV."],
    examples: [
      {
        title: "Two-column TSV",
        input: "id\tname\n1\tAda\n2\tGrace",
        output: "id,name\n1,Ada\n2,Grace",
        explanation: "Tabs are replaced with commas between cells.",
      },
    ],
    faqs: [
      faq("Are quotes handled?", "Values containing commas or quotes are escaped in CSV output."),
      faq("Can I convert CSV back to TSV?", "Use spreadsheet export tools or a future reverse converter."),
      faq("Does this support headers?", "Yes. The first row is preserved as CSV headers."),
    ],
    commonUseCases: ["Convert database TSV exports", "Prepare spreadsheet imports", "Normalize tabular data formats"],
  }),
  buildLiveTool({
    id: "base64-encode",
    slug: "base64-encode",
    title: "Base64 Encoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/base64-encode/",
    shortDescription: "Encode text and strings to Base64 for APIs, tokens, and data transfer.",
    metaTitle: "Base64 Encoder - Encode Text to Base64 Online",
    metaDescription: "Encode text to Base64 online. Convert strings to Base64 for APIs, auth headers, and data transfer.",
    keywords: ["base64 encode", "text to base64"],
    relatedTools: ["base64-decode", "url-encode", "hash-generator"],
    componentKey: "GenericEncoderTool",
    explanation: "Encode plain text into Base64 strings instantly in your browser.",
    howToUse: ["Paste text to encode.", "Copy the Base64 output.", "Use the decoder to reverse the result."],
    examples: [{ title: "Simple text", input: "Hello world", output: "SGVsbG8gd29ybGQ=", explanation: "UTF-8 text is encoded to Base64." }],
    faqs: [
      faq("Does this support Unicode?", "Yes. UTF-8 text is encoded safely."),
      faq("Can I decode the result?", "Yes. Use the Base64 Decoder tool."),
      faq("Is data sent to a server?", "No. Encoding happens locally."),
    ],
    commonUseCases: ["Prepare API auth strings", "Encode small payloads for testing", "Generate Base64 samples"],
  }),
  buildLiveTool({
    id: "base64-decode",
    slug: "base64-decode",
    title: "Base64 Decoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/base64-decode/",
    shortDescription: "Decode Base64 strings back to readable text.",
    metaTitle: "Base64 Decoder - Decode Base64 Online",
    metaDescription: "Decode Base64 strings online. Convert Base64 text back to readable UTF-8 output instantly.",
    keywords: ["base64 decode", "decode base64"],
    relatedTools: ["base64-encode", "url-decode", "hash-generator"],
    componentKey: "GenericEncoderTool",
    explanation: "Decode Base64 strings into readable text output.",
    howToUse: ["Paste a Base64 string.", "Review decoded text.", "Copy the readable output."],
    examples: [{ title: "Sample decode", input: "SGVsbG8gd29ybGQ=", output: "Hello world", explanation: "Base64 is decoded to UTF-8 text." }],
    faqs: [
      faq("What if the string is invalid?", "You will see a clear invalid Base64 error."),
      faq("Can I encode again?", "Yes. Use the Base64 Encoder tool."),
      faq("Are line breaks supported?", "Trim whitespace before decoding for best results."),
    ],
    commonUseCases: ["Inspect API token payloads", "Decode debug strings", "Reverse Base64 test fixtures"],
  }),
  buildLiveTool({
    id: "url-encode",
    slug: "url-encode",
    title: "URL Encoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/url-encode/",
    shortDescription: "Percent-encode strings for safe URL query parameters.",
    metaTitle: "URL Encoder - Percent Encode Strings Online",
    metaDescription: "URL encode text online. Percent-encode strings for safe query parameters and URI components.",
    keywords: ["url encode", "percent encode"],
    relatedTools: ["url-decode", "base64-encode", "utm-builder"],
    componentKey: "GenericEncoderTool",
    explanation: "Encode special characters for safe use in URLs and query strings.",
    howToUse: ["Enter text to encode.", "Copy the encoded output.", "Use in URLs or query parameters."],
    examples: [{ title: "Query value", input: "hello world & more", output: "hello%20world%20%26%20more", explanation: "Spaces and symbols are percent-encoded." }],
    faqs: [
      faq("Is this the same as encodeURIComponent?", "Yes. It uses standard URI component encoding."),
      faq("Can I decode the output?", "Use the URL Decoder tool."),
      faq("Should I encode full URLs?", "Encode individual query values rather than entire URLs when possible."),
    ],
    commonUseCases: ["Build query strings manually", "Encode search terms", "Prepare URL parameter tests"],
  }),
  buildLiveTool({
    id: "url-decode",
    slug: "url-decode",
    title: "URL Decoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/url-decode/",
    shortDescription: "Decode percent-encoded URL strings back to readable text.",
    metaTitle: "URL Decoder - Decode Percent-Encoded URLs Online",
    metaDescription: "URL decode percent-encoded strings online. Convert encoded query values back to readable text.",
    keywords: ["url decode", "percent decode"],
    relatedTools: ["url-encode", "utm-parser", "base64-decode"],
    componentKey: "GenericEncoderTool",
    explanation: "Decode percent-encoded URL components into readable text.",
    howToUse: ["Paste an encoded string or query value.", "Copy decoded output.", "Use the encoder for the reverse step."],
    examples: [{ title: "Encoded phrase", input: "hello%20world", output: "hello world", explanation: "%20 becomes a space." }],
    faqs: [
      faq("Can I decode full URLs?", "Yes, though decoding individual query values is often clearer."),
      faq("What about invalid sequences?", "Invalid encoding returns an error message."),
      faq("Does this change plus signs?", "Plus signs are handled according to standard decodeURIComponent behavior."),
    ],
    commonUseCases: ["Inspect encoded analytics parameters", "Debug query strings", "Read encoded redirect values"],
  }),
  buildLiveTool({
    id: "html-encode",
    slug: "html-encode",
    title: "HTML Entity Encoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/html-encode/",
    shortDescription: "Escape HTML special characters for safe rendering in documents.",
    metaTitle: "HTML Entity Encoder - Escape HTML Online",
    metaDescription: "HTML encode text online. Escape special characters like <, >, and & for safe HTML rendering.",
    keywords: ["html encode", "html escape"],
    relatedTools: ["url-encode", "base64-encode", "case-converter"],
    componentKey: "GenericEncoderTool",
    explanation: "Escape HTML-sensitive characters to prevent markup interpretation.",
    howToUse: ["Paste HTML or text with special characters.", "Copy encoded entities.", "Paste into HTML templates safely."],
    examples: [{ title: "Escape markup", input: '<div>Price & value</div>', output: "&lt;div&gt;Price &amp; value&lt;/div&gt;", explanation: "Tags and ampersands are escaped." }],
    faqs: [
      faq("Does this encode all Unicode?", "Common HTML special characters are escaped reliably."),
      faq("Can I decode entities here?", "Use a dedicated HTML decode tool if added later."),
      faq("Is this for full documents?", "It is best for snippets, attributes, and escaped text nodes."),
    ],
    commonUseCases: ["Escape user-generated content", "Prepare safe HTML examples", "Sanitize demo snippets"],
  }),
  buildLiveTool({
    id: "sql-formatter",
    slug: "sql-formatter",
    title: "SQL Formatter",
    category: "developer-tools",
    subcategory: "formatters-validators",
    pathOverride: "/developer-tools/sql-formatter/",
    shortDescription: "Pretty-print and minify SQL queries for readability and review.",
    metaTitle: "SQL Formatter - Format SQL Online",
    metaDescription: "Format SQL online. Pretty-print or minify SQL queries for readability, code review, and documentation.",
    keywords: ["sql formatter", "format sql"],
    relatedTools: ["json-formatter", "css-formatter", "csv-to-json"],
    componentKey: "GenericFormatterTool",
    explanation: "Format SQL queries with clearer line breaks or compact minified output.",
    howToUse: ["Paste a SQL query.", "Choose Format or Minify.", "Copy the formatted SQL."],
    examples: [{ title: "Select query", input: "SELECT id, name FROM users WHERE active = true", output: "SELECT id, name\nFROM users\nWHERE active = true", explanation: "Major SQL clauses are placed on separate lines." }],
    faqs: [
      faq("Does this validate SQL syntax?", "It focuses on formatting, not full dialect validation."),
      faq("Can it minify queries?", "Yes. Use the Minify action for compact output."),
      faq("Which SQL dialects are supported?", "Common keyword formatting works for most ANSI-style SQL."),
    ],
    commonUseCases: ["Clean up copied SQL snippets", "Prepare queries for documentation", "Review long SQL statements"],
  }),
  buildLiveTool({
    id: "css-formatter",
    slug: "css-formatter",
    title: "CSS Formatter",
    category: "developer-tools",
    subcategory: "formatters-validators",
    pathOverride: "/developer-tools/css-formatter/",
    shortDescription: "Format and minify CSS stylesheets for readability or production.",
    metaTitle: "CSS Formatter - Format CSS Online",
    metaDescription: "Format CSS online. Pretty-print or minify CSS stylesheets for development, review, and production use.",
    keywords: ["css formatter", "format css", "minify css"],
    relatedTools: ["json-formatter", "sql-formatter", "html-encode"],
    componentKey: "GenericFormatterTool",
    explanation: "Format CSS with indentation or minify it for smaller payloads.",
    howToUse: ["Paste CSS.", "Choose Format or Minify.", "Copy the output."],
    examples: [{ title: "Simple rule", input: "body{margin:0;color:#111;}", output: "body {\n  margin:0;\n  color:#111;\n}", explanation: "Rules and declarations are expanded for readability." }],
    faqs: [
      faq("Does this remove comments when minifying?", "Yes. Comments are removed in minify mode."),
      faq("Can it validate CSS?", "It formats CSS but does not perform full linting."),
      faq("Will custom properties be preserved?", "Yes. Declarations remain intact during formatting."),
    ],
    commonUseCases: ["Clean copied CSS snippets", "Minify styles for demos", "Review stylesheet changes"],
  }),
  buildLiveTool({
    id: "uuid-generator",
    slug: "uuid-generator",
    title: "UUID Generator",
    category: "developer-tools",
    subcategory: "generators",
    pathOverride: "/developer-tools/uuid-generator/",
    shortDescription: "Generate random UUID v4 identifiers for apps, tests, and databases.",
    metaTitle: "UUID Generator - Generate UUID v4 Online",
    metaDescription: "Generate UUID v4 identifiers online. Create random UUIDs for apps, test data, and database records.",
    keywords: ["uuid generator", "generate uuid"],
    relatedTools: ["hash-generator", "lorem-ipsum-generator", "json-formatter"],
    componentKey: "GenericGeneratorTool",
    explanation: "Generate RFC-style UUID v4 values instantly in the browser.",
    howToUse: ["Click Generate UUID.", "Copy the result.", "Generate again for additional IDs."],
    examples: [{ title: "Sample UUID", input: "Generate", output: "3fa85f64-5717-4562-b3fc-2c963f66afa6", explanation: "Each click creates a new random UUID v4." }],
    faqs: [
      faq("Are UUIDs cryptographically random?", "Modern browsers use crypto.randomUUID when available."),
      faq("Can I bulk generate IDs?", "Click generate repeatedly or use future batch features."),
      faq("Which UUID version is used?", "This tool generates UUID v4 values."),
    ],
    commonUseCases: ["Create test record IDs", "Generate sample API identifiers", "Prototype database schemas"],
  }),
  buildLiveTool({
    id: "hash-generator",
    slug: "hash-generator",
    title: "Hash Generator",
    category: "developer-tools",
    subcategory: "generators",
    pathOverride: "/developer-tools/hash-generator/",
    shortDescription: "Generate SHA-256 hash digests from text for checksums and testing.",
    metaTitle: "Hash Generator - SHA-256 Hash Online",
    metaDescription: "Generate SHA-256 hashes online. Create hash digests from text for checksums, testing, and verification.",
    keywords: ["hash generator", "sha256", "sha-256"],
    relatedTools: ["uuid-generator", "base64-encode", "json-formatter"],
    componentKey: "GenericGeneratorTool",
    explanation: "Create SHA-256 hash digests from pasted text using Web Crypto.",
    howToUse: ["Paste text to hash.", "Click Generate.", "Copy the SHA-256 digest."],
    examples: [{ title: "Hash example", input: "hello", output: "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e6245a594fb40c2e25528a8b5b8", explanation: "The same input always produces the same SHA-256 hash." }],
    faqs: [
      faq("Is my text uploaded?", "No. Hashing runs locally via Web Crypto."),
      faq("Which algorithms are supported?", "This version generates SHA-256 digests."),
      faq("Can I verify files?", "This first version hashes pasted text only."),
    ],
    commonUseCases: ["Generate checksums for strings", "Create test hash fixtures", "Compare hashed values in development"],
  }),
  buildLiveTool({
    id: "lorem-ipsum-generator",
    slug: "lorem-ipsum-generator",
    title: "Lorem Ipsum Generator",
    category: "developer-tools",
    subcategory: "generators",
    pathOverride: "/developer-tools/lorem-ipsum-generator/",
    shortDescription: "Generate placeholder text for mockups, prototypes, and page layouts.",
    metaTitle: "Lorem Ipsum Generator - Placeholder Text Online",
    metaDescription: "Generate lorem ipsum placeholder text online for mockups, wireframes, and design prototypes.",
    keywords: ["lorem ipsum generator", "placeholder text"],
    relatedTools: ["uuid-generator", "word-counter", "case-converter"],
    componentKey: "GenericGeneratorTool",
    explanation: "Generate lorem ipsum paragraphs for design and development placeholders.",
    howToUse: ["Choose number of paragraphs.", "Click Generate.", "Copy the placeholder text."],
    examples: [{ title: "One paragraph", input: "1 paragraph", output: "Lorem ipsum dolor sit amet...", explanation: "Paragraph count controls output length." }],
    faqs: [
      faq("How many paragraphs can I generate?", "Up to 10 paragraphs in this version."),
      faq("Is the text random each time?", "Paragraph length varies slightly by count setting."),
      faq("Can I use this in commercial mockups?", "Yes. Placeholder text is free to use."),
    ],
    commonUseCases: ["Fill design mockups", "Test text wrapping layouts", "Populate prototype pages"],
  }),
  buildLiveTool({
    id: "json-validator",
    slug: "json-validator",
    title: "JSON Validator",
    category: "developer-tools",
    subcategory: "formatters-validators",
    pathOverride: "/developer-tools/json-validator/",
    shortDescription: "Validate JSON syntax and catch parse errors instantly.",
    metaTitle: "JSON Validator - Check JSON Syntax Online",
    metaDescription:
      "Validate JSON online. Paste JSON to check syntax, find parse errors, and confirm your data is valid before using it in apps.",
    keywords: ["json validator", "validate json", "json syntax checker", "check json online", "json lint"],
    relatedTools: ["json-formatter", "json-to-csv", "yaml-to-json", "csv-to-json"],
    componentKey: "GenericValidatorTool",
    explanation: "Paste JSON to validate syntax before sending to APIs, saving configs, or converting to other formats.",
    howToUse: ["Paste JSON text.", "Click Validate.", "Fix any reported syntax errors and re-validate."],
    examples: [
      { title: "Valid object", input: '{"name":"Ada","active":true}', output: "Valid JSON ✓", explanation: "Parses without errors." },
      { title: "Invalid trailing comma", input: '{"name":"Ada",}', output: "Invalid JSON error", explanation: "Trailing commas are not allowed in standard JSON." },
    ],
    faqs: [
      faq("Does this format JSON?", "Use the JSON Formatter to pretty-print or minify valid JSON."),
      faq("Can I validate large JSON files?", "Large payloads depend on browser memory. Very large files may be slow."),
      faq("Is my JSON uploaded?", "No. Validation runs locally in your browser."),
    ],
    commonUseCases: ["Debug API response syntax", "Validate config files before deploy", "Check JSON before CSV conversion"],
  }),
  buildLiveTool({
    id: "regex-tester",
    slug: "regex-tester",
    title: "Regex Tester",
    category: "developer-tools",
    subcategory: "formatters-validators",
    pathOverride: "/developer-tools/regex-tester/",
    shortDescription: "Test regular expressions with live match highlighting and capture groups.",
    metaTitle: "Regex Tester - Test Regular Expressions Online",
    metaDescription:
      "Test regex patterns online. See matches, indexes, and capture groups with configurable flags.",
    keywords: ["regex tester", "regular expression tester", "regex checker"],
    relatedTools: ["json-validator", "json-formatter", "jwt-decoder"],
    componentKey: "RegexTesterTool",
    explanation: "Test regular expressions against sample text with global and case-insensitive flags.",
    howToUse: ["Enter a regex pattern.", "Paste test text.", "Review matches and capture groups."],
    examples: [
      {
        title: "Email pattern",
        input: "pattern=[a-z]+@[a-z]+, text=hello@example.com",
        output: "1 match at index 0",
        explanation: "Simple email-like pattern match.",
      },
    ],
    faqs: [
      faq("Which regex flavor?", "JavaScript RegExp syntax as used in browsers and Node.js."),
      faq("Are capture groups shown?", "Yes. Match list shows text, index, and groups."),
      faq("Is my text uploaded?", "No. Testing runs locally in your browser."),
    ],
    commonUseCases: ["Debug regex for validation rules", "Extract groups from log lines", "Test patterns before code deploy"],
  }),
  buildLiveTool({
    id: "jwt-decoder",
    slug: "jwt-decoder",
    title: "JWT Decoder",
    category: "developer-tools",
    subcategory: "encoders-decoders",
    pathOverride: "/developer-tools/jwt-decoder/",
    shortDescription: "Decode JWT header and payload locally for debugging. Signature not verified.",
    metaTitle: "JWT Decoder - Decode JWT Token Online",
    metaDescription:
      "Decode JWT tokens online. Inspect header and payload JSON locally. Signature verification not included.",
    keywords: ["jwt decoder", "decode jwt token", "jwt parser"],
    relatedTools: ["base64-decode", "json-formatter", "regex-tester"],
    componentKey: "JwtDecoderTool",
    explanation: "Paste a JWT to decode its header and payload segments for debugging OAuth and API tokens.",
    howToUse: ["Paste a JWT token.", "Click Decode.", "Review header, payload, and exp/iat timestamps."],
    examples: [
      {
        title: "Sample token",
        input: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        output: "Header and payload JSON",
        explanation: "Base64url segments decode to JSON objects.",
      },
    ],
    faqs: [
      faq("Is the signature verified?", "No. This tool decodes only; it does not validate signatures."),
      faq("Are tokens sent to a server?", "No. Decoding runs locally in your browser."),
      faq("Can I decode Bearer tokens?", "Yes. A leading Bearer prefix is stripped automatically."),
    ],
    commonUseCases: ["Debug OAuth access tokens", "Inspect JWT claims during development", "Check token expiration"],
  }),
  buildLiveTool({
    id: "csv-to-html-table",
    slug: "csv-to-html-table",
    title: "CSV to HTML Table",
    category: "developer-tools",
    subcategory: "data-converters",
    pathOverride: "/developer-tools/csv-to-html-table/",
    shortDescription: "Convert CSV data into a styled HTML table snippet for emails and web pages.",
    metaTitle: "CSV to HTML Table - Convert CSV to HTML Online",
    metaDescription:
      "Convert CSV to HTML table online. Generate styled table markup for emails, docs, and web pages.",
    keywords: ["csv to html table", "csv to html converter", "csv html table generator"],
    relatedTools: ["csv-to-json", "json-to-csv", "markdown-to-html"],
    componentKey: "CsvToHtmlTableTool",
    explanation: "Paste CSV or upload a file to generate an HTML table with optional striped and bordered styles.",
    howToUse: ["Paste CSV or drop a file.", "Choose table styling options.", "Copy the HTML snippet."],
    examples: [
      {
        title: "Two-column CSV",
        input: "name,email\nAda,ada@example.com",
        output: "<table>...</table>",
        explanation: "First row becomes table headers.",
      },
    ],
    faqs: [
      faq("Can I upload a CSV file?", "Yes. Drag and drop or select a CSV file."),
      faq("Is inline CSS included?", "Yes. Basic styles are embedded for email-friendly snippets."),
      faq("Does this support TSV?", "Tab and semicolon delimiters are auto-detected when possible."),
    ],
    commonUseCases: ["Embed tables in HTML emails", "Generate report snippets", "Preview CSV as a web table"],
  }),
  buildLiveTool({
    id: "cron-builder",
    slug: "cron-builder",
    title: "Cron Expression Builder",
    category: "developer-tools",
    subcategory: "generators",
    pathOverride: "/developer-tools/cron-builder/",
    shortDescription: "Build cron schedules visually and copy Unix cron expressions.",
    metaTitle: "Cron Expression Builder - Cron Schedule Generator",
    metaDescription:
      "Build Unix cron expressions online. Use presets or custom fields and copy the schedule.",
    keywords: ["cron expression generator", "cron builder", "cron schedule generator"],
    relatedTools: ["uuid-generator", "json-formatter", "hash-generator"],
    componentKey: "CronBuilderTool",
    explanation: "Build standard five-field cron expressions with presets or custom minute/hour/day fields.",
    howToUse: ["Choose a preset or enter custom fields.", "Click Build expression.", "Copy the cron string."],
    examples: [
      {
        title: "Daily at 9 AM",
        input: "minute=0, hour=9, day=*, month=*, dow=*",
        output: "0 9 * * *",
        explanation: "Runs every day at 09:00.",
      },
    ],
    faqs: [
      faq("Which cron format?", "Standard five-field Unix cron: minute hour day month day-of-week."),
      faq("Can I use wildcards?", "Yes. * and ranges like 1-5 or */15 are supported in field validation."),
      faq("Does this run jobs?", "No. This only builds the expression string."),
    ],
    commonUseCases: ["Schedule CI/CD jobs", "Configure server crontab entries", "Document job schedules"],
  }),
  buildLiveTool({
    id: "password-generator",
    slug: "password-generator",
    title: "Password Generator",
    category: "developer-tools",
    subcategory: "generators",
    pathOverride: "/developer-tools/password-generator/",
    shortDescription: "Generate secure random passwords and passphrases locally in your browser.",
    metaTitle: "Password Generator - Secure Random Password Online",
    metaDescription:
      "Generate secure passwords and passphrases online. Customize length and character sets. Runs locally with no upload.",
    keywords: ["password generator", "random password generator", "passphrase generator"],
    relatedTools: ["uuid-generator", "hash-generator", "jwt-decoder"],
    componentKey: "PasswordGeneratorTool",
    explanation: "Create random passwords or word-based passphrases with estimated entropy feedback.",
    howToUse: ["Choose password or passphrase mode.", "Set length and character options.", "Generate and copy the result."],
    examples: [
      {
        title: "16-character password",
        input: "length=16, upper+lower+numbers+symbols",
        output: "Random 16-character string",
        explanation: "Uses crypto.getRandomValues when available.",
      },
    ],
    faqs: [
      faq("Are passwords stored?", "No. Generation runs locally and nothing is saved."),
      faq("What is passphrase mode?", "Random words joined with a separator for memorable high-entropy passwords."),
      faq("Should I reuse passwords?", "No. Use a unique password for each account and a password manager."),
    ],
    commonUseCases: ["Create account passwords", "Generate API test credentials", "Produce memorable passphrases"],
  }),
];
