import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "finance-calculators";

export const financeLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "mortgage-calculator-pro",
    slug: "mortgage-calculator-pro",
    title: "Mortgage Calculator with Amortization",
    category,
    subcategory: "loans-payments",
    shortDescription:
      "Calculate PITI payments, amortization schedules, extra payments, and home affordability.",
    metaTitle: "Mortgage Calculator with Amortization - PITI & Affordability",
    metaDescription:
      "Free mortgage calculator with PITI breakdown, full amortization schedule, extra payment modeling, and affordability reverse-solve. No login required.",
    keywords: [
      "mortgage calculator",
      "amortization calculator",
      "mortgage payment calculator",
      "piti calculator",
    ],
    relatedTools: [
      "loan-payment-calculator",
      "compound-interest-calculator",
      "rental-deal-analyzer",
      "mortgage-calculator",
    ],
    componentKey: "MortgageCalculatorProTool",
    schemaType: "Calculator",
    priority: 1,
    formula: "M = P × [r(1+r)^n] / [(1+r)^n − 1]; total monthly = P&I + tax + insurance + PMI + HOA",
    explanation:
      "Estimate monthly mortgage payments with a full PITI breakdown, generate an amortization schedule, model extra payments, or reverse-solve how much house you can afford.",
    howToUse: [
      "Choose Payment, Amortization, Extra payments, or Affordability mode.",
      "Enter home price, down payment, rate, and term.",
      "Add property tax, insurance, PMI, and HOA for total monthly cost.",
      "Download the amortization schedule as CSV when ready.",
    ],
    examples: [
      {
        title: "$450K home, 20% down, 30-year fixed",
        input: "home=450000, down=90000, rate=6.5%, tax=4200/yr",
        output: "P&I plus PITI total with amortization table",
        explanation: "Standard owner-occupied purchase estimate.",
      },
    ],
    faqs: [
      faq("What is PITI?", "Principal, interest, taxes, and insurance — your total housing payment."),
      faq("How is PMI estimated?", "If LTV exceeds 80%, a default ~0.5% annual PMI estimate applies unless you override it."),
      faq("Can I export the schedule?", "Yes. Download CSV from the Amortization or Extra payments tab."),
      faq("Is this financial advice?", "No. Rates and costs vary; use for planning estimates only."),
    ],
    commonUseCases: [
      "Estimate monthly payment before making an offer",
      "Compare extra payment scenarios",
      "Find max affordable home price from income and DTI",
    ],
    assumptions: [
      "Fixed-rate fully amortizing loan unless extra payment mode changes payoff.",
      "Affordability mode uses target DTI minus existing debts and escrow.",
    ],
    sourceNotes: [
      "Standard US mortgage amortization formula.",
      "Use the simple loan payment calculator for non-mortgage loans.",
    ],
  }),
  buildLiveTool({
    id: "percentage-calculator",
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    category,
    subcategory: "percentages",
    shortDescription: "Calculate percentages, increases, and decreases.",
    metaTitle: "Percentage Calculator - Calculate Percent Online",
    metaDescription: "Calculate what a percentage of a value is. Free percentage calculator with instant results in your browser.",
    keywords: ["percentage calculator", "percent calculator", "calculate percentage"],
    relatedTools: ["discount-calculator", "margin-calculator", "markup-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "result = value × (percent ÷ 100)",
    explanation: "Find what percentage of a number equals a given percent value.",
    howToUse: ["Enter the base value.", "Enter the percentage.", "View the calculated result instantly."],
    examples: [{ title: "15% of 200", input: "value=200, percent=15", output: "30", explanation: "200 × 0.15 = 30." }],
    faqs: [
      faq("Can I calculate percent increase?", "Use the discount or markup calculators for price change scenarios."),
      faq("What if I enter zero?", "A zero value returns zero result; negative values are supported."),
      faq("Is this financial advice?", "No. This is a simple math calculator for estimates."),
    ],
    commonUseCases: ["Calculate sales tax amounts", "Find commission on a sale", "Compute tip percentages"],
  }),
  buildLiveTool({
    id: "tip-calculator",
    slug: "tip-calculator",
    title: "Tip Calculator",
    category,
    subcategory: "everyday-finance",
    shortDescription: "Calculate tips and split bills between people.",
    metaTitle: "Tip Calculator - Split Bills and Calculate Tips",
    metaDescription: "Calculate tip amount, total bill, and per-person split. Free tip calculator for restaurants and group dining.",
    keywords: ["tip calculator", "bill splitter", "gratuity calculator"],
    relatedTools: ["percentage-calculator", "discount-calculator", "loan-payment-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "tip = bill × (tip% ÷ 100); per person = (bill + tip) ÷ people",
    explanation: "Enter bill amount, tip percentage, and number of people to split the total.",
    howToUse: ["Enter the bill amount.", "Set tip percentage and number of people.", "View tip, total, and per-person amounts."],
    examples: [{ title: "$80 bill, 20% tip, 4 people", input: "bill=80, tip=20, people=4", output: "tip $16, total $96, $24/person", explanation: "Tip is 20% of $80; total split four ways." }],
    faqs: [
      faq("Does it include tax?", "Enter the bill total you want to tip on, including tax if desired."),
      faq("Can I split unevenly?", "This tool splits the total equally among people."),
      faq("What tip percentage is standard?", "15–20% is common in the US; adjust to your preference."),
    ],
    commonUseCases: ["Restaurant dining with friends", "Split delivery orders", "Quick gratuity estimates"],
  }),
  buildLiveTool({
    id: "discount-calculator",
    slug: "discount-calculator",
    title: "Discount Calculator",
    category,
    subcategory: "percentages",
    shortDescription: "Calculate sale prices after percentage discounts.",
    metaTitle: "Discount Calculator - Sale Price After Discount",
    metaDescription: "Calculate discounted sale prices from original price and discount percentage. Free discount calculator online.",
    keywords: ["discount calculator", "sale price calculator", "percent off calculator"],
    relatedTools: ["percentage-calculator", "margin-calculator", "markup-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "sale price = original price − (original price × discount %)",
    explanation: "See discount savings and final sale price from an original price and discount rate.",
    howToUse: ["Enter original price.", "Enter discount percentage.", "View savings and sale price."],
    examples: [{ title: "25% off $120", input: "price=120, discount=25", output: "sale price $90, savings $30", explanation: "120 × 0.25 = $30 off." }],
    faqs: [
      faq("Can discount exceed 100%?", "Enter realistic discount percentages for meaningful results."),
      faq("Does it handle tax?", "No. This calculates pre-tax sale price only."),
      faq("Can I use decimal discounts?", "Yes. Enter values like 12.5 for 12.5% off."),
    ],
    commonUseCases: ["Compare sale prices", "Calculate Black Friday savings", "Verify store discount labels"],
  }),
  buildLiveTool({
    id: "margin-calculator",
    slug: "margin-calculator",
    title: "Profit Margin Calculator",
    category,
    subcategory: "percentages",
    shortDescription: "Calculate profit margin from cost and selling price.",
    metaTitle: "Profit Margin Calculator - Calculate Margin Percent",
    metaDescription: "Calculate profit margin percentage from cost and selling price. Free margin calculator for products and services.",
    keywords: ["margin calculator", "profit margin", "gross margin calculator"],
    relatedTools: ["markup-calculator", "break-even-calculator", "discount-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "margin % = (price − cost) ÷ price × 100",
    explanation: "Estimate gross margin and profit dollars from cost and selling price.",
    howToUse: ["Enter product cost.", "Enter selling price.", "View margin percentage and profit dollars."],
    examples: [{ title: "Cost $40, price $100", input: "cost=40, price=100", output: "60% margin, $60 profit", explanation: "(100−40)÷100 = 60%." }],
    faqs: [
      faq("Is this gross or net margin?", "Gross margin based on cost and price only; excludes overhead."),
      faq("What if price equals cost?", "Margin is 0% with zero profit."),
      faq("Can selling price be below cost?", "Yes, but margin will be negative indicating a loss."),
    ],
    commonUseCases: ["Price products for target margin", "Evaluate supplier quotes", "Compare SKU profitability"],
  }),
  buildLiveTool({
    id: "markup-calculator",
    slug: "markup-calculator",
    title: "Markup Calculator",
    category,
    subcategory: "percentages",
    shortDescription: "Calculate markup percentage and selling price from cost.",
    metaTitle: "Markup Calculator - Calculate Markup and Price",
    metaDescription: "Calculate markup amount and selling price from cost and markup percentage. Free markup calculator online.",
    keywords: ["markup calculator", "markup percentage", "pricing calculator"],
    relatedTools: ["margin-calculator", "break-even-calculator", "discount-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "selling price = cost × (1 + markup % ÷ 100)",
    explanation: "Apply a markup percentage to cost to get a target selling price.",
    howToUse: ["Enter product cost.", "Enter markup percentage.", "View selling price and markup dollars."],
    examples: [{ title: "50% markup on $80 cost", input: "cost=80, markup=50", output: "price $120, markup $40", explanation: "80 × 1.5 = $120." }],
    faqs: [
      faq("How is markup different from margin?", "Markup is based on cost; margin is based on selling price."),
      faq("Can I target a specific price?", "Enter cost and adjust markup until the price matches your goal."),
      faq("Does it include tax?", "No. This is a pre-tax pricing estimate."),
    ],
    commonUseCases: ["Retail pricing decisions", "Service rate setting", "Wholesale-to-retail conversion"],
  }),
  buildLiveTool({
    id: "compound-interest-calculator",
    slug: "compound-interest-calculator",
    title: "Compound Interest Calculator",
    category,
    subcategory: "investment-basics",
    shortDescription: "Project compound interest growth over time.",
    metaTitle: "Compound Interest Calculator - Future Value Estimate",
    metaDescription: "Project compound interest growth from principal, rate, years, and compounding frequency. Free investment estimate calculator.",
    keywords: ["compound interest calculator", "interest calculator", "future value calculator"],
    relatedTools: ["loan-payment-calculator", "break-even-calculator", "roi-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "A = P(1 + r/n)^(nt)",
    explanation: "Estimate future value and interest earned with compound growth assumptions.",
    howToUse: ["Enter principal, annual rate, years, and compounding periods per year.", "View future value and total interest."],
    examples: [{ title: "$10,000 at 5% for 10 years, compounded monthly", input: "P=10000, r=5, t=10, n=12", output: "≈ $16,470 future value", explanation: "Monthly compounding grows faster than annual." }],
    faqs: [
      faq("Is this investment advice?", "No. This is an estimate using fixed inputs."),
      faq("What compounding frequency should I use?", "12 for monthly, 4 for quarterly, 1 for annual."),
      faq("Does it account for contributions?", "No. Only initial principal compounds in this version."),
    ],
    commonUseCases: ["Estimate savings growth", "Compare compound vs simple interest", "Plan long-term investment scenarios"],
    assumptions: ["Fixed rate for entire period.", "No withdrawals or additional deposits.", "Estimate only—not financial advice."],
  }),
  buildLiveTool({
    id: "loan-payment-calculator",
    slug: "loan-payment-calculator",
    title: "Loan Payment Calculator",
    category,
    subcategory: "loans-payments",
    shortDescription: "Calculate monthly loan payments and total paid.",
    metaTitle: "Loan Payment Calculator - Monthly Payment Estimate",
    metaDescription: "Calculate monthly loan payments from amount, interest rate, and term. Free loan payment calculator online.",
    keywords: ["loan payment calculator", "monthly payment calculator", "loan calculator"],
    relatedTools: ["mortgage-calculator", "compound-interest-calculator", "break-even-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "M = P × [r(1+r)^n] ÷ [(1+r)^n − 1]",
    explanation: "Estimate monthly payment and total amount paid over the loan term using standard amortization.",
    howToUse: ["Enter loan amount, annual interest rate, and term in years.", "View monthly payment and total paid."],
    examples: [{ title: "$20,000 loan at 6% for 5 years", input: "amount=20000, rate=6, years=5", output: "≈ $387/month", explanation: "Standard fixed-rate amortization formula." }],
    faqs: [
      faq("Does this include fees or insurance?", "No. Only principal and interest on the loan amount."),
      faq("What if rate is zero?", "Payment equals principal divided by number of months."),
      faq("Is this a loan offer?", "No. This is an estimate for planning purposes."),
    ],
    commonUseCases: ["Compare auto loan offers", "Estimate personal loan payments", "Plan debt repayment"],
    assumptions: ["Fixed interest rate.", "Equal monthly payments.", "Estimate only—not financial advice."],
  }),
  buildLiveTool({
    id: "break-even-calculator",
    slug: "break-even-calculator",
    title: "Break-Even Calculator",
    category,
    subcategory: "investment-basics",
    shortDescription: "Find break-even point for fixed and variable costs.",
    metaTitle: "Break-Even Calculator - Units to Break Even",
    metaDescription: "Calculate break-even units from fixed costs, price per unit, and variable cost per unit. Free business calculator.",
    keywords: ["break even calculator", "break-even point", "business calculator"],
    relatedTools: ["margin-calculator", "markup-calculator", "loan-payment-calculator"],
    componentKey: "GenericFinanceCalculatorTool",
    schemaType: "Calculator",
    formula: "break-even units = fixed costs ÷ (price − variable cost)",
    explanation: "Find how many units must be sold to cover fixed and variable costs.",
    howToUse: ["Enter fixed costs, price per unit, and variable cost per unit.", "View break-even units and revenue."],
    examples: [{ title: "Fixed $5000, price $50, variable $20", input: "fixed=5000, price=50, variable=20", output: "167 units to break even", explanation: "5000 ÷ (50−20) ≈ 166.67 units." }],
    faqs: [
      faq("What if price equals variable cost?", "Break-even is undefined—you must price above variable cost."),
      faq("Can I use negative costs?", "Enter positive realistic values for meaningful results."),
      faq("Does it include tax?", "No. Use pre-tax unit economics."),
    ],
    commonUseCases: ["Launch product planning", "Evaluate pricing strategy", "Estimate sales targets"],
  }),
];
