import type { ToolDefinition } from "./types";
import { buildLiveTool, faq } from "./registry-live-helpers";

const category = "image-tools";

export const imageLiveTools: ToolDefinition[] = [
  buildLiveTool({
    id: "png-to-jpg",
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    category,
    subcategory: "format-converters",
    shortDescription: "Convert PNG images to JPG for smaller file sizes. HEIC/HEIF also supported.",
    metaTitle: "PNG to JPG Converter - Convert PNG Online",
    metaDescription: "Convert PNG or HEIC images to JPG in your browser. Free converter with before/after file size and local processing.",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg"],
    relatedTools: ["jpg-to-png", "image-compressor", "image-resizer"],
    componentKey: "PngToJpgTool",
    explanation: "Upload a PNG and download a JPG version using browser canvas image processing. Nothing leaves your device.",
    howToUse: [
      "Drop or select a PNG file.",
      "Click Convert image to process locally in your browser.",
      "Download the JPG output.",
    ],
    examples: [
      {
        title: "Logo PNG to JPG",
        input: "512×512 PNG screenshot",
        output: "512×512 JPG at 92% quality",
        explanation: "Typical use for reducing file size before email or web upload.",
      },
    ],
    faqs: [
      faq("Will transparency be preserved?", "No. JPG does not support transparency; transparent areas become white or black depending on the canvas."),
      faq("What quality is used?", "The converter exports JPG at 92% quality by default."),
      faq("Does the image leave my browser?", "No. Conversion runs locally on your device with no server upload."),
      faq("Can I convert iPhone HEIC photos?", "Yes. HEIC and HEIF files are auto-converted to JPEG before processing."),
    ],
    commonUseCases: ["Reduce PNG file size for web uploads", "Convert screenshots for email attachments", "Prepare images for CMS size limits"],
  }),
  buildLiveTool({
    id: "jpg-to-png",
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    category,
    subcategory: "format-converters",
    shortDescription: "Convert JPG images to PNG format.",
    metaTitle: "JPG to PNG Converter - Convert JPEG Online",
    metaDescription: "Convert JPG or JPEG images to PNG in your browser. Free JPG to PNG converter with download.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png"],
    relatedTools: ["png-to-jpg", "image-resizer", "svg-to-png"],
    componentKey: "JpgToPngTool",
    explanation: "Upload a JPG/JPEG image and download a lossless PNG version.",
    howToUse: ["Upload a JPG or JPEG file.", "Click Process image.", "Download the PNG output."],
    examples: [
      {
        title: "Photo JPG to PNG",
        input: "1200×800 JPEG photo",
        output: "1200×800 PNG file",
        explanation: "Useful when you need lossless editing or transparency overlay workflows.",
      },
    ],
    faqs: [
      faq("Will file size increase?", "Often yes. PNG is lossless and may produce larger files than JPG."),
      faq("Can I convert JPEG and JPG?", "Yes. Both extensions are accepted."),
      faq("Is quality lost?", "No additional compression is applied beyond the source JPG decode."),
    ],
    commonUseCases: ["Prepare images for design tools", "Convert photos before adding transparency", "Export web images as PNG"],
  }),
  buildLiveTool({
    id: "png-to-ico",
    slug: "png-to-ico",
    title: "PNG to ICO Converter",
    category,
    subcategory: "format-converters",
    shortDescription: "Convert PNG images to multi-size ICO favicon files.",
    metaTitle: "PNG to ICO Converter - Create Favicon ICO",
    metaDescription: "Convert PNG images to real ICO favicon files with 16×16, 32×32, and 48×48 sizes. Free PNG to ICO converter.",
    keywords: ["png to ico", "png to favicon", "favicon from png"],
    relatedTools: ["favicon-generator", "svg-to-png", "png-to-jpg"],
    componentKey: "PngToIcoTool",
    explanation: "Upload a PNG and download a proper ICO file containing 16×16, 32×32, and 48×48 embedded PNG images.",
    howToUse: [
      "Upload a square or high-resolution PNG.",
      "Click Process image to build the ICO.",
      "Download the .ico file for use as a favicon.",
    ],
    examples: [
      {
        title: "App icon to favicon",
        input: "256×256 PNG logo",
        output: "favicon.ico with 16, 32, and 48 px sizes",
        explanation: "Windows and browsers accept ICO files with multiple embedded sizes.",
      },
    ],
    faqs: [
      faq("Is this a real ICO file?", "Yes. The output is a standard ICO container with embedded PNG images."),
      faq("What sizes are included?", "16×16, 32×32, and 48×48 pixels."),
      faq("Should I use a square source?", "Square PNGs produce the best favicon results."),
    ],
    commonUseCases: ["Create website favicons", "Generate Windows app icons", "Convert logo PNGs for browser tabs"],
  }),
  buildLiveTool({
    id: "svg-to-png",
    slug: "svg-to-png",
    title: "SVG to PNG Converter",
    category,
    subcategory: "format-converters",
    shortDescription: "Rasterize SVG graphics to PNG at custom sizes.",
    metaTitle: "SVG to PNG Converter - Rasterize SVG Online",
    metaDescription: "Convert SVG files to PNG at custom width and height. Free SVG to PNG converter in your browser.",
    keywords: ["svg to png", "convert svg to png", "rasterize svg"],
    relatedTools: ["png-to-jpg", "image-resizer", "favicon-generator"],
    componentKey: "SvgToPngTool",
    explanation: "Upload an SVG and export a PNG at your chosen dimensions. Works best with self-contained SVGs without external references.",
    howToUse: [
      "Upload an SVG file.",
      "Set target width and height in pixels.",
      "Process and download the PNG.",
    ],
    examples: [
      {
        title: "Icon SVG at 512px",
        input: "Simple SVG icon",
        output: "512×512 PNG raster",
        explanation: "Default export size is 512×512 if dimensions are not changed.",
      },
    ],
    faqs: [
      faq("Do external fonts or images work?", "SVGs that reference external assets may not render correctly in the browser."),
      faq("Can I set custom dimensions?", "Yes. Enter width and height before processing."),
      faq("Is vector quality preserved?", "PNG is raster output; use higher dimensions for sharper results."),
    ],
    commonUseCases: ["Export icons for app stores", "Convert vector logos to PNG", "Generate PNG assets from SVG designs"],
    assumptions: ["Self-contained SVG files render most reliably.", "External CSS, fonts, or linked images may not load."],
  }),
  buildLiveTool({
    id: "image-resizer",
    slug: "image-resizer",
    title: "Image Resizer",
    category,
    subcategory: "resizers-compressors",
    shortDescription: "Resize images to exact width and height dimensions.",
    metaTitle: "Image Resizer - Resize Images Online",
    metaDescription: "Resize images to exact width and height in your browser. Free online image resizer with download.",
    keywords: ["image resizer", "resize image online", "resize photo"],
    relatedTools: ["image-compressor", "png-to-jpg", "dpi-calculator"],
    componentKey: "ImageResizerTool",
    explanation: "Set target width and height, then download the resized image while preserving the original format where possible.",
    howToUse: ["Upload an image.", "Enter width and height.", "Process and download."],
    examples: [
      {
        title: "Resize to thumbnail",
        input: "1920×1080 photo",
        output: "320×180 image",
        explanation: "Scale down large images for thumbnails or social previews.",
      },
    ],
    faqs: [
      faq("Does it maintain aspect ratio?", "The tool resizes to exact dimensions entered; adjust width and height to preserve ratio manually."),
      faq("What formats are supported?", "Common browser-readable formats including PNG, JPG, WebP, and HEIC/HEIF."),
      faq("Will quality decrease?", "Downscaling generally looks fine; upscaling may appear soft or pixelated."),
    ],
    commonUseCases: ["Create thumbnails", "Resize photos for web forms", "Prepare images for social media specs"],
  }),
  buildLiveTool({
    id: "image-compressor",
    slug: "image-compressor",
    title: "Image Compressor",
    category,
    subcategory: "resizers-compressors",
    shortDescription: "Reduce image file size with adjustable JPEG quality.",
    metaTitle: "Image Compressor - Compress Images Online",
    metaDescription: "Compress images by adjusting JPEG quality in your browser. Free image compressor with download.",
    keywords: ["image compressor", "compress image online", "reduce image size"],
    relatedTools: ["image-resizer", "png-to-jpg", "jpg-to-png"],
    componentKey: "ImageCompressorTool",
    explanation: "Upload an image and export a compressed JPEG at your chosen quality level between 0.1 and 1.",
    howToUse: ["Upload an image.", "Set JPEG quality (0.1–1).", "Process and download the compressed JPG."],
    examples: [
      {
        title: "Compress photo at 70% quality",
        input: "2 MB JPG photo",
        output: "Smaller JPG at quality 0.7",
        explanation: "Lower quality values produce smaller files with more visible compression.",
      },
    ],
    faqs: [
      faq("What output format is used?", "Output is always JPEG regardless of input format."),
      faq("What quality should I use?", "0.7–0.85 is a common range for web photos."),
      faq("Can I compress PNG?", "Yes, but output will be converted to JPEG."),
      faq("Does it support HEIC from iPhone?", "Yes. HEIC/HEIF files are converted locally before compression."),
    ],
    commonUseCases: ["Reduce email attachment size", "Optimize images before upload", "Shrink hero images for faster pages"],
  }),
  buildLiveTool({
    id: "favicon-generator",
    slug: "favicon-generator",
    title: "Favicon Generator",
    category,
    subcategory: "icons-favicons",
    shortDescription: "Generate a favicon bundle with PNG sizes and ICO file.",
    metaTitle: "Favicon Generator - Create Favicon Bundle",
    metaDescription: "Generate favicon PNG sizes and favicon.ico in a downloadable ZIP bundle. Free favicon generator in your browser.",
    keywords: ["favicon generator", "create favicon", "favicon from image"],
    relatedTools: ["png-to-ico", "svg-to-png", "image-resizer"],
    componentKey: "FaviconGeneratorTool",
    explanation: "Upload a source image and download a ZIP containing favicon PNGs (16–256 px) plus a multi-size favicon.ico file.",
    howToUse: [
      "Upload a square logo or icon.",
      "Click Process image.",
      "Download the ZIP bundle with all favicon sizes.",
    ],
    examples: [
      {
        title: "Website favicon bundle",
        input: "512×512 logo PNG",
        output: "ZIP with 16, 32, 48, 64, 128, 256 px PNGs + favicon.ico",
        explanation: "Includes common sizes used by browsers, PWA manifests, and app icons.",
      },
    ],
    faqs: [
      faq("What is in the ZIP?", "PNG files for each size plus a favicon.ico with embedded multi-size images."),
      faq("What source image works best?", "Square, high-resolution PNGs with simple shapes work best."),
      faq("Can I use just the ICO?", "Yes. The ZIP includes favicon.ico alongside individual PNG files."),
    ],
    commonUseCases: ["Launch a new website", "Create PWA icon sets", "Generate favicons for static site generators"],
  }),
  buildLiveTool({
    id: "dpi-calculator",
    slug: "dpi-calculator",
    title: "DPI Calculator",
    category,
    subcategory: "print-dpi-tools",
    shortDescription: "Calculate print DPI from pixel and print dimensions.",
    metaTitle: "DPI Calculator - Print Resolution Calculator",
    metaDescription: "Calculate print DPI from pixel dimensions and print size in inches. Free DPI calculator.",
    keywords: ["dpi calculator", "print dpi", "pixels to dpi"],
    relatedTools: ["image-resizer", "svg-to-png", "png-to-jpg"],
    componentKey: "GenericDesignTool",
    schemaType: "Calculator",
    formula: "DPI = pixels ÷ print inches",
    explanation: "Enter pixel dimensions and intended print size in inches to estimate effective print DPI.",
    howToUse: [
      "Enter pixel width and height.",
      "Enter intended print width and height in inches.",
      "View calculated DPI for each dimension.",
    ],
    examples: [
      {
        title: "3000 px photo printed at 10 inches",
        input: "3000 px width, 10 in print width",
        output: "300 DPI",
        explanation: "3000 ÷ 10 = 300 DPI, suitable for high-quality print.",
      },
    ],
    faqs: [
      faq("What DPI is good for print?", "300 DPI is common for photo-quality print; 150 DPI may suffice for large formats."),
      faq("Does this resize my image?", "No. This calculator only estimates DPI from dimensions."),
      faq("Can width and height DPI differ?", "Yes, if pixel and print aspect ratios do not match."),
    ],
    commonUseCases: ["Check if an image is print-ready", "Plan poster or photo print sizes", "Estimate resolution before sending to a printer"],
    sourceNotes: ["DPI = dots per inch = pixels per inch for digital images."],
  }),
];
